#include "AdminMaps.hpp"

std::map<const char*, const wchar_t*> itemsMap = {
    { "Advanced Bullet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_AdvancedBullet.PrimalItemAmmo_AdvancedBullet_C'"},
    { "Advanced Rifle Bullet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_AdvancedRifleBullet.PrimalItemAmmo_AdvancedRifleBullet_C'"},
    { "Advanced Sniper Bullet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_AdvancedSniperBullet.PrimalItemAmmo_AdvancedSniperBullet_C'"},
    { "Stone Arrow", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_ArrowStone.PrimalItemAmmo_ArrowStone_C'"},
    { "Toxicant Arrow", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_ArrowToxin.PrimalItemAmmo_ArrowToxin_C'"},
    { "Tranq Arrow", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_ArrowTranq.PrimalItemAmmo_ArrowTranq_C'"},
    { "Ballista Arrow", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_BallistaArrow.PrimalItemAmmo_BallistaArrow_C'"},
    { "Boulder", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_Boulder.PrimalItemAmmo_Boulder_C'"},
    { "Cannon Ball", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_CannonBall.PrimalItemAmmo_CannonBall_C'"},
    { "Metal Arrow", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_CompoundBowArrow.PrimalItemAmmo_CompoundBowArrow_C'"},
    { "Dodo Arrow", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_DodoArrow.PrimalItemAmmo_DodoArrow_C'"},
    { "Grappling Hook", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_GrapplingHook.PrimalItemAmmo_GrapplingHook_C'"},
    { "Simple Bullet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_SimpleBullet.PrimalItemAmmo_SimpleBullet_C'"},
    { "Simple Rifle Bullet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_SimpleRifleBullet.PrimalItemAmmo_SimpleRifleBullet_C'"},
    { "Shotgun Bullet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_SimpleShotgunBullet.PrimalItemAmmo_SimpleShotgunBullet_C'"},
    { "Tranq Dart", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_TranqDart.PrimalItemAmmo_TranqDart_C'"},
    { "Pheramone Dart", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_AggroTranqDart.PrimalItemAmmo_AggroTranqDart_C'"},
    { "Rocket", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_Rocket.PrimalItemAmmo_Rocket_C'"},
    { "Tox Dart", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItemAmmo_RefinedTranqDart.PrimalItemAmmo_RefinedTranqDart_C'"},
    { "C4 Ammo", L"Blueprint'/Game/PrimalEarth/Test/PrimalItemC4Ammo.PrimalItemC4Ammo_C'"},
    { "Facricated Sniper", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponMachinedSniper.PrimalItem_WeaponMachinedSniper_C'"},
    { "Fabricated Pistol", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponMachinedPistol.PrimalItem_WeaponMachinedPistol_C'"},
    { "Fabricated Shotgun", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponMachinedShotgun.PrimalItem_WeaponMachinedShotgun_C'"},
    { "Longneck Rifle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponOneShotRifle.PrimalItem_WeaponOneShotRifle_C'"},
    { "Assult Rifle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponRifle.PrimalItem_WeaponRifle_C'"},
    { "Launcher RPG", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponRocketLauncher.PrimalItem_WeaponRocketLauncher_C'"},
    { "Shotgun", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponShotgun.PrimalItem_WeaponShotgun_C'"},
    { "C4 Detonator", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponC4.PrimalItem_WeaponC4_C'"},
    { "Metal Bow", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponCompoundBow.PrimalItem_WeaponCompoundBow_C'"},
    { "Crossbow", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponCrossbow.PrimalItem_WeaponCrossbow_C'"},
    { "Flare Gun", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponFlareGun.PrimalItem_WeaponFlareGun_C'"},
    { "Simple Pistol", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponGun.PrimalItem_WeaponGun_C'"},
    { "Rocket Turret", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_TurretRocket.PrimalItemStructure_TurretRocket_C'"},
    { "Tek Rifle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_TekRifle.PrimalItem_TekRifle_C'"},
    { "Eery Element", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Resources/PrimalItemResource_EeryElement.PrimalItemResource_EeryElement_C'"},
    { "SoothingBalm Major", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_SoothingBalm_Major.PrimalItemConsumable_SoothingBalm_Major_C'"},
    { "SoothingBalm", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_SoothingBalm.PrimalItemConsumable_SoothingBalm_C'"},
    { "SoothingBalm Minor", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_SoothingBalm_Minor.PrimalItemConsumable_SoothingBalm_Minor_C'"},
    { "Dragon Fly Wings", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Misc/Special/PrimalItem_DragonFlyWings.PrimalItem_DragonFlyWings_C'"},
    { "Weapon Iron Skillet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponIronSkillet.PrimalItem_WeaponIronSkillet_C'"},
    { "Weapon Crowbar", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponCrowbar.PrimalItem_WeaponCrowbar_C'"},
    { "Weapon Cutlass", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponCutlass.PrimalItem_WeaponCutlass_C'"},
    { "Eerie Turret", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_Eerie_Turret.PrimalItemStructure_Eerie_Turret_C'"},
    { "Race Flag", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimaItemStructure_RaceFlag.PrimaItemStructure_RaceFlag_C'"},
    { "Resurrect Platform", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Structures/Misc/PrimalItemStructure_ResurrectPlatform.PrimalItemStructure_ResurrectPlatform_C'"},
    { "Weapon Super Gun", L"Blueprint'/Game/Mobile/Pursuits/Caves/TributeRewards/PrimalItem_WeaponSuperGun.PrimalItem_WeaponSuperGun_C'"},
    { "Vampire Eyes", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_VampireEyes.PrimalItemSkin_VampireEyes_C'" },
    { "Hunter Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemArmor_HunterHat.PrimalItemArmor_HunterHat_C'"},
    { "Antenna Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_Antenna.PrimalItemSkin_Antenna_C'"},
    { "Beta Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_BetaHat.PrimalItemSkin_BetaHat_C'"},
    { "Egg Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_BrokenEggHat.PrimalItemSkin_BrokenEggHat_C'"},
    { "Bunny Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_BunnyEarsHat.PrimalItemSkin_BunnyEarsHat_C'"},
    { "Captain Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_CaptainHat.PrimalItemSkin_CaptainHat_C'"},
    { "Cat Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_CatMask.PrimalItemSkin_CatMask_C'"},
    { "Chick Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ChickHat.PrimalItemSkin_ChickHat_C'"},
    { "Chili Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ChiliHelmet.PrimalItemSkin_ChiliHelmet_C'"},
    { "Clown Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ClownMask.PrimalItemSkin_ClownMask_C'"},
    { "Devil Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DevilHorns.PrimalItemSkin_DevilHorns_C'"},
    { "Dilo Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DiloMask.PrimalItemSkin_DiloMask_C'"},
    { "Dino Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DinoHat.PrimalItemSkin_DinoHat_C'"},
    { "Dodorex Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DodorexMask.PrimalItemSkin_DodorexMask_C'"},
    { "Dodowyvern Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DodowyvernHat.PrimalItemSkin_DodowyvernHat_C'"},
    { "Dot Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DogMask.PrimalItemSkin_DogMask_C'"},
    { "Explorer Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ExplorerHat.PrimalItemSkin_ExplorerHat_C'"},
    { "GoldCrown Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_GoldCrown.PrimalItemSkin_GoldCrown_C'"},
    { "Halo Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_HaloHat.PrimalItemSkin_HaloHat_C'"},
    { "Manticore Boots", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreBoots.PrimalItemSkin_ManticoreBoots_C'"},
    { "Manticore Gloves", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreGloves.PrimalItemSkin_ManticoreGloves_C'"},
    { "Manticore Helmet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreHelmet.PrimalItemSkin_ManticoreHelmet_C'"},
    { "Manticore Pants", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticorePants.PrimalItemSkin_ManticorePants_C'"},
    { "Manticore Shield", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreShield.PrimalItemSkin_ManticoreShield_C'"},
    { "Manticore Shirt", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreShirt.PrimalItemSkin_ManticoreShirt_C'"},
    { "Party Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_PartyHat.PrimalItemSkin_PartyHat_C'"},
    { "Razer Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_RazerHat.PrimalItemSkin_RazerHat_C'"},
    { "Santa Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_SantaHat.PrimalItemSkin_SantaHat_C'"},
    { "Skull Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_SkullMask.PrimalItemSkin_SkullMask_C'"},
    { "Spinner Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_SpinnerHat.PrimalItemSkin_SpinnerHat_C'"},
    { "Top Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_TopHat.PrimalItemSkin_TopHat_C'"},
    { "Turkey Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_TurkeyHat.PrimalItemSkin_TurkeyHat_C'"},
    { "Vampire Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_VampireEyes.PrimalItemSkin_VampireEyes_C'"},
    { "Werewolf Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_WerewolfHat.PrimalItemSkin_WerewolfHat_C'"},
    { "Witch Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_WitchHat.PrimalItemSkin_WitchHat_C'"},
    { "Graft Lava", L"Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Lava.PrimalItem_ImplantGraft_Lava_C'"},
    { "Graft Eerie", L"Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Eerie.PrimalItem_ImplantGraft_Eerie_C'"},
    { "Graft Yahweh", L"Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Yahweh.PrimalItem_ImplantGraft_Yahweh_C'"},
    { "Graft Camo", L"Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Camo.PrimalItem_ImplantGraft_Camo_C'"},
    { "Graft Colorbomb", L"Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Colorbomb.PrimalItem_ImplantGraft_Colorbomb_C'"},
    { "Feast", L"Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_Feast.PrimalItemConsumable_Feast_C'" },
    { "Intense Focus", L"Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_IntenseFocus.PrimalItemConsumable_IntenseFocus_C'" },
    { "Leg Day", L"Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_LegDay.PrimalItemConsumable_LegDay_C'" },
    { "Thick Skin", L"Blueprint'/Game/PrimalEarth/Test/PrimalItemConsumable_ThickSkin.PrimalItemConsumable_ThickSkin_C'" },
    { "Herbivore Pheromone", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_PheromoneHerb.PrimalItemConsumable_PheromoneHerb_C'" },
    { "Carno Pheromone", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_PheromoneMeat.PrimalItemConsumable_PheromoneMeat_C'" },
    { "Generic Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDyeGeneric.PrimalItemDyeGeneric_C'"},
    { "Magenta2 Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_ActuallyMagenta.PrimalItemDye_ActuallyMagenta_C'"},
    { "Black Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Black.PrimalItemDye_Black_C'"},
    { "Blue Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Blue.PrimalItemDye_Blue_C'"},
    { "Brick Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Brick.PrimalItemDye_Brick_C'"},
    { "Brown Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Brown.PrimalItemDye_Brown_C'"},
    { "Cantaloupe Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Cantaloupe.PrimalItemDye_Cantaloupe_C'"},
    { "Cyan Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Cyan.PrimalItemDye_Cyan_C'"},
    { "Forest Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Forest.PrimalItemDye_Forest_C'"},
    { "Green Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Green.PrimalItemDye_Green_C'"},
    { "Magenta Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Magenta.PrimalItemDye_Magenta_C'"},
    { "Mud Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Mud.PrimalItemDye_Mud_C'"},
    { "Navy Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Navy.PrimalItemDye_Navy_C'"},
    { "Olive Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Olive.PrimalItemDye_Olive_C'"},
    { "Orange Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Orange.PrimalItemDye_Orange_C'"},
    { "Parchment Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Parchment.PrimalItemDye_Parchment_C'"},
    { "Pink Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Pink.PrimalItemDye_Pink_C'"},
    { "Purple Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Purple.PrimalItemDye_Purple_C'"},
    { "Red Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Red.PrimalItemDye_Red_C'"},
    { "Royal Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Royalty.PrimalItemDye_Royalty_C'"},
    { "Silver Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Silver.PrimalItemDye_Silver_C'"},
    { "Sky Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Sky.PrimalItemDye_Sky_C'"},
    { "Slate Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Slate.PrimalItemDye_Slate_C'"},
    { "Tan Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Tan.PrimalItemDye_Tan_C'"},
    { "Tangerine Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Tangerine.PrimalItemDye_Tangerine_C'"},
    { "White Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_White.PrimalItemDye_White_C'"},
    { "Yellow Dye", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItemDye_Yellow.PrimalItemDye_Yellow_C'"},
    { "Dodo Sail", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItem_DodoSail.PrimalItem_DodoSail_C'"},
    { "Dungeon Key", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItem_DungeonAccessKey.PrimalItem_DungeonAccessKey_C'"},
    { "Evil Bear", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItem_ImprintBoost_CuddleBear_Black.PrimalItem_ImprintBoost_CuddleBear_Black_C'"},
    { "Yoyo", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItem_MatureBoost_Toy_Yoyo.PrimalItem_MatureBoost_Toy_Yoyo_C'"},
    { "Paddle Ball", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItem_MatureBoost_Toy_PaddleBall.PrimalItem_MatureBoost_Toy_PaddleBall_C'"},
    { "Jump Rope", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/PrimalItem_MatureBoost_Toy_JumpRope.PrimalItem_MatureBoost_Toy_JumpRope_C'"},
    { "Frog Feet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/ARKetypes/PrimalItemArmor_FrogFeet.PrimalItemArmor_FrogFeet_C'"},
    { "Metal Bit", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Bits/PrimalItem_MetalBit.PrimalItem_MetalBit_C'"},
    { "Plucker Bit", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Bits/PrimalItem_PluckerBit.PrimalItem_PluckerBit_C'"},
    { "Hat Tribute Dino", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Cloth/PrimalItem_HatTributeDino.PrimalItem_HatTributeDino_C'"},
    { "Hat Tribute Player", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Cloth/PrimalItem_HatTributePlayer.PrimalItem_HatTributePlayer_C'"},
    { "Bandanna", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Collars/PrimalItemArmor_Bandana.PrimalItemArmor_Bandana_C'"},
    { "Base Collar", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Collars/PrimalItemArmor_BaseCollar.PrimalItemArmor_BaseCollar_C'"},
    { "Chain Collar", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Collars/PrimalItemArmor_ChainCollar.PrimalItemArmor_ChainCollar_C'"},
    { "Comfy Collar", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Collars/PrimalItemArmor_ComfyCollar.PrimalItemArmor_ComfyCollar_C'"},
    { "Cone of Shame", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Collars/PrimalItemArmor_ConeofShame.PrimalItemArmor_ConeofShame_C'"},
    { "Fancy Collar", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Collars/PrimalItemArmor_FancyCollar.PrimalItemArmor_FancyCollar_C'"},
    { "Gold Chain", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Collars/PrimalItemArmor_GoldenChain.PrimalItemArmor_GoldenChain_C'"},
    { "Simple Collar", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Collars/PrimalItemArmor_SimpleCollar.PrimalItemArmor_SimpleCollar_C'"},
    { "Spiked Collar", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Collars/PrimalItemArmor_SpikedCollar.PrimalItemArmor_SpikedCollar_C'"},
    { "Birthday Pants", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemSkin_BirthdayPants.PrimalItemSkin_BirthdayPants_C'"},
    { "Birthday Shirt", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemSkin_BirthdayShirt.PrimalItemSkin_BirthdayShirt_C'"},
    { "Bone Helmet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemSkin_BoneHelmet.PrimalItemSkin_BoneHelmet_C'"},
    { "Candy Club", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemSkin_CandyClub.PrimalItemSkin_CandyClub_C'"},
    { "Witch Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemSkin_DinoWitchHat.PrimalItemSkin_DinoWitchHat_C'"},
    { "Fish Club", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemSkin_FishClub.PrimalItemSkin_FishClub_C'"},
    { "Firework Flaregun", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemSkin_FlaregunFireworks.PrimalItemSkin_FlaregunFireworks_C'"},
    { "Nerdy Glasses", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemSkin_Glasses.PrimalItemSkin_Glasses_C'"},
    { "Firework Launcher", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemSkin_RocketLauncherFireworks.PrimalItemSkin_RocketLauncherFireworks_C'"},
    { "Fur Gloves", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Fur/PrimalItemArmor_FurGloves.PrimalItemArmor_FurGloves_C'"},
    { "Fur Helmet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Fur/PrimalItemArmor_FurHelmet.PrimalItemArmor_FurHelmet_C'"},
    { "Fur Pants", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Fur/PrimalItemArmor_FurPants.PrimalItemArmor_FurPants_C'"},
    { "Fur Boots", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Fur/PrimalItemArmor_FurBoots.PrimalItemArmor_FurBoots_C'"},
    { "Fur Shirt", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Fur/PrimalItemArmor_FurShirt.PrimalItemArmor_FurShirt_C'"},
    { "Ghillie Gloves", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Ghillie/PrimalItemArmor_GhillieGloves.PrimalItemArmor_GhillieGloves_C'"},
    { "Ghillie Boots", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Ghillie/PrimalItemArmor_GhillieBoots.PrimalItemArmor_GhillieBoots_C'"},
    { "Ghillie Pants", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Ghillie/PrimalItemArmor_GhilliePants.PrimalItemArmor_GhilliePants_C'"},
    { "Ghillie Helmet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Ghillie/PrimalItemArmor_GhillieHelmet.PrimalItemArmor_GhillieHelmet_C'"},
    { "Ghillie Shirt", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Ghillie/PrimalItemArmor_GhillieShirt.PrimalItemArmor_GhillieShirt_C'"},
    { "Hide Boots", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemArmor_HideBoots.PrimalItemArmor_HideBoots_C'"},
    { "Hide Gloves", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemArmor_HideGloves.PrimalItemArmor_HideGloves_C'"},
    { "Hide Helmet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemArmor_HideHelmet.PrimalItemArmor_HideHelmet_C'"},
    { "Hide Pants", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemArmor_HidePants.PrimalItemArmor_HidePants_C'"},
    { "Hide Shirt", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemArmor_HideShirt.PrimalItemArmor_HideShirt_C'"},
    { "Skin Torch Sparkler", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItemSkin_TorchSparkler.PrimalItemSkin_TorchSparkler_C'"},
    { "Skin DevHat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItem_Skin_Account_DevKitMaster.PrimalItem_Skin_Account_DevKitMaster_C'"},
    { "Skin GameTester", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItem_Skin_Account_GameTester.PrimalItem_Skin_Account_GameTester_C'"},
    { "Skin Wildcard", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Leather/PrimalItem_Skin_Account_WildcardAdmin.PrimalItem_Skin_Account_WildcardAdmin_C'"},
    { "Flak Boots", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Metal/PrimalItemArmor_MetalBoots.PrimalItemArmor_MetalBoots_C'"},
    { "Flak Gloves", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Metal/PrimalItemArmor_MetalGloves.PrimalItemArmor_MetalGloves_C'"},
    { "Flak Helmet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Metal/PrimalItemArmor_MetalHelmet.PrimalItemArmor_MetalHelmet_C'"},
    { "Flak Pants", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Metal/PrimalItemArmor_MetalPants.PrimalItemArmor_MetalPants_C'"},
    { "Flak Shirt", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Metal/PrimalItemArmor_MetalShirt.PrimalItemArmor_MetalShirt_C'"},
    { "Miner Helmet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Metal/PrimalItemArmor_MinersHelmet.PrimalItemArmor_MinersHelmet_C'"},
    { "Riot Boots", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Riot/PrimalItemArmor_RiotBoots.PrimalItemArmor_RiotBoots_C'"},
    { "Riot Gloves", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Riot/PrimalItemArmor_RiotGloves.PrimalItemArmor_RiotGloves_C'"},
    { "Riot Helmet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Riot/PrimalItemArmor_RiotHelmet.PrimalItemArmor_RiotHelmet_C'"},
    { "Riot Pants", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Riot/PrimalItemArmor_RiotPants.PrimalItemArmor_RiotPants_C'"},
    { "Riot Shirt", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Riot/PrimalItemArmor_RiotShirt.PrimalItemArmor_RiotShirt_C'"},
    { "Allo Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_AlloSaddle.PrimalItemArmor_AlloSaddle_C'"},
    { "Anky Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_AnkyloSaddle.PrimalItemArmor_AnkyloSaddle_C'"},
    { "Argy Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ArgentavisSaddle.PrimalItemArmor_ArgentavisSaddle_C'"},
    { "Arthro Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ArthroSaddle.PrimalItemArmor_ArthroSaddle_C'"},
    { "Baryonyx Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_BaryonyxSaddle.PrimalItemArmor_BaryonyxSaddle_C'"},
    { "Basilo Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_BasiloSaddle.PrimalItemArmor_BasiloSaddle_C'"},
    { "Casteroides Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_BeaverSaddle.PrimalItemArmor_BeaverSaddle_C'"},
    { "Carno Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_CarnoSaddle.PrimalItemArmor_CarnoSaddle_C'"},
    { "Chalico Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ChalicoSaddle.PrimalItemArmor_ChalicoSaddle_C'"},
    { "Daeodon Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_DaeodonSaddle.PrimalItemArmor_DaeodonSaddle_C'"},
    { "Diplodocus Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_DiplodocusSaddle.PrimalItemArmor_DiplodocusSaddle_C'"},
    { "DireBear Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_DireBearSaddle.PrimalItemArmor_DireBearSaddle_C'"},
    { "Doedic Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_DoedSaddle.PrimalItemArmor_DoedSaddle_C'"},
    { "Dolphin Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_DolphinSaddle.PrimalItemArmor_DolphinSaddle_C'"},
    { "Dunkleo Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_DunkleosteusSaddle.PrimalItemArmor_DunkleosteusSaddle_C'"},
    { "Equus Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_EquusSaddle.PrimalItemArmor_EquusSaddle_C'"},
    { "Galli Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_Gallimimus.PrimalItemArmor_Gallimimus_C'"},
    { "Giga Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_GigantSaddle.PrimalItemArmor_GigantSaddle_C'"},
    { "Iguanadon Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_IguanodonSaddle.PrimalItemArmor_IguanodonSaddle_C'"},
    { "Kapro Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_KaprosuchusSaddle.PrimalItemArmor_KaprosuchusSaddle_C'"},
    { "Mammoth Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MammothSaddle.PrimalItemArmor_MammothSaddle_C'"},
    { "Mammoth Platform Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MammothSaddle_Platform.PrimalItemArmor_MammothSaddle_Platform_C'"},
    { "Manta Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MantaSaddle.PrimalItemArmor_MantaSaddle_C'"},
    { "Megalodon Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MegalodonSaddle.PrimalItemArmor_MegalodonSaddle_C'"},
    { "Tek Megalodon Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MegalodonSaddle_Tek.PrimalItemArmor_MegalodonSaddle_Tek_C'"},
    { "Megalosaurus Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MegalosaurusSaddle.PrimalItemArmor_MegalosaurusSaddle_C'"},
    { "Megatherium Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MegatheriumSaddle.PrimalItemArmor_MegatheriumSaddle_C'"},
    { "Mosasaur Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MosaSaddle.PrimalItemArmor_MosaSaddle_C'"},
    { "Mosasaur Platform Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MosaSaddle_Platform.PrimalItemArmor_MosaSaddle_Platform_C'"},
    { "Mosasaur Tek Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_MosaSaddle_Tek.PrimalItemArmor_MosaSaddle_Tek_C'"},
    { "Pachyrhino Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PachyrhinoSaddle.PrimalItemArmor_PachyrhinoSaddle_C'"},
    { "Pachy Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PachySaddle.PrimalItemArmor_PachySaddle_C'"},
    { "Paracer Platform Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ParacerSaddle_Platform.PrimalItemArmor_ParacerSaddle_Platform_C'"},
    { "Paracer Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_Paracer_Saddle.PrimalItemArmor_Paracer_Saddle_C'"},
    { "Parasaur Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ParaSaddle.PrimalItemArmor_ParaSaddle_C'"},
    { "Parasuar Saddle 2", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ParaSaddle_Launch.PrimalItemArmor_ParaSaddle_Launch_C'"},
    { "Pelagornis Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PelaSaddle.PrimalItemArmor_PelaSaddle_C'"},
    { "Phiomia Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PhiomiaSaddle.PrimalItemArmor_PhiomiaSaddle_C'"},
    { "Plesi Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PlesiaSaddle.PrimalItemArmor_PlesiaSaddle_C'"},
    { "Plesi Platform Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PlesiSaddle_Platform.PrimalItemArmor_PlesiSaddle_Platform_C'"},
    { "Procoptodon Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ProcoptodonSaddle.PrimalItemArmor_ProcoptodonSaddle_C'"},
    { "Pteranodon Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_PteroSaddle.PrimalItemArmor_PteroSaddle_C'"},
    { "Quetz Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_QuetzSaddle.PrimalItemArmor_QuetzSaddle_C'"},
    { "Quetz Plat Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_QuetzSaddle_Platform.PrimalItemArmor_QuetzSaddle_Platform_C'"},
    { "Raptor Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_RaptorSaddle.PrimalItemArmor_RaptorSaddle_C'"},
    { "Rex Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_RexSaddle.PrimalItemArmor_RexSaddle_C'"},
    { "Tek Rex Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_RexSaddle_Tek.PrimalItemArmor_RexSaddle_Tek_C'"},
    { "Rhino Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_RhinoSaddle.PrimalItemArmor_RhinoSaddle_C'"},
    { "Sabertooth Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SaberSaddle.PrimalItemArmor_SaberSaddle_C'"},
    { "Sabertooth Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SaberSaddle.PrimalItemArmor_SaberSaddle_C'"},
    { "GENERIC Tek Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SaddleGeneric_Tek.PrimalItemArmor_SaddleGeneric_Tek_C'"},
    { "Sarco Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SarcoSaddle.PrimalItemArmor_SarcoSaddle_C'"},
    { "Bronto Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SauroSaddle.PrimalItemArmor_SauroSaddle_C'"},
    { "Bronto Plat Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SauroSaddle_Platform.PrimalItemArmor_SauroSaddle_Platform_C'"},
    { "Scorpian Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ScorpionSaddle.PrimalItemArmor_ScorpionSaddle_C'"},
    { "Araneo Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SpiderSaddle.PrimalItemArmor_SpiderSaddle_C'"},
    { "Spino Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_SpinoSaddle.PrimalItemArmor_SpinoSaddle_C'"},
    { "Megalocerus Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_StagSaddle.PrimalItemArmor_StagSaddle_C'"},
    { "Stego Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_StegoSaddle.PrimalItemArmor_StegoSaddle_C'"},
    { "Tapejara Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TapejaraSaddle.PrimalItemArmor_TapejaraSaddle_C'"},
    { "Tapejara Tek Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_Tapejara_Tek.PrimalItemArmor_Tapejara_Tek_C'"},
    { "Terror Bird Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TerrorBirdSaddle.PrimalItemArmor_TerrorBirdSaddle_C'"},
    { "Therizino Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TherizinosaurusSaddle.PrimalItemArmor_TherizinosaurusSaddle_C'"},
    { "Titanosaur Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TitanSaddle_Platform.PrimalItemArmor_TitanSaddle_Platform_C'"},
    { "Beelzebufo Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_ToadSaddle.PrimalItemArmor_ToadSaddle_C'"},
    { "Trike Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TrikeSaddle.PrimalItemArmor_TrikeSaddle_C'"},
    { "Carbonemys Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TurtleSaddle.PrimalItemArmor_TurtleSaddle_C'"},
    { "Tusoteuthis Saddle", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemArmor_TusoSaddle.PrimalItemArmor_TusoSaddle_C'"},
    { "Raptor Saddle 2", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_AnimeRaptor.PrimalItemCostume_AnimeRaptor_C'"},
    { "Bone Carno Costume", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneCarno.PrimalItemCostume_BoneCarno_C'"},
    { "Bone Giga Costume", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneGigant.PrimalItemCostume_BoneGigant_C'"},
    { "Bone Quetz Costume", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneQuetz.PrimalItemCostume_BoneQuetz_C'"},
    { "Bone Raptor Costume", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneRaptor.PrimalItemCostume_BoneRaptor_C'"},
    { "Bone Rex Costume", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneRex.PrimalItemCostume_BoneRex_C'"},
    { "Bone Bronto Costume", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneSauro.PrimalItemCostume_BoneSauro_C'"},
    { "Bone Stego Costume", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneStego.PrimalItemCostume_BoneStego_C'"},
    { "Bone Trike Costume", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Saddles/PrimalItemCostume_BoneTrike.PrimalItemCostume_BoneTrike_C'"},
    { "Gas Mask", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/SCUBA/PrimalItemArmor_GasMask.PrimalItemArmor_GasMask_C'"},
    { "Night Vision Goggles", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/SCUBA/PrimalItemArmor_NightVisionGoggles.PrimalItemArmor_NightVisionGoggles_C'"},
    { "SCUBA Flippers", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/SCUBA/PrimalItemArmor_ScubaBoots_Flippers.PrimalItemArmor_ScubaBoots_Flippers_C'"},
    { "SCUBA Goggles", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/SCUBA/PrimalItemArmor_ScubaHelmet_Goggles.PrimalItemArmor_ScubaHelmet_Goggles_C'"},
    { "SCUBA Pants", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/SCUBA/PrimalItemArmor_ScubaPants.PrimalItemArmor_ScubaPants_C'"},
    { "SCUBA Tank", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/SCUBA/PrimalItemArmor_ScubaShirt_SuitWithTank.PrimalItemArmor_ScubaShirt_SuitWithTank_C'"},
    { "Metal Shield", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_MetalShield.PrimalItemArmor_MetalShield_C'"},
    { "Tek Shield", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_ShieldTek.PrimalItemArmor_ShieldTek_C'"},
    { "Riot Shield", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Shields/PrimalItemArmor_TransparentRiotShield.PrimalItemArmor_TransparentRiotShield_C'"},
    { "Skin Hunter Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemArmor_HunterHat.PrimalItemArmor_HunterHat_C'"},
    { "Skin Antenna Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_Antenna.PrimalItemSkin_Antenna_C'"},
    { "Skin Beta Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_BetaHat.PrimalItemSkin_BetaHat_C'"},
    { "Skin Egg Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_BrokenEggHat.PrimalItemSkin_BrokenEggHat_C'"},
    { "Skin Bunny Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_BunnyEarsHat.PrimalItemSkin_BunnyEarsHat_C'"},
    { "Skin Captain Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_CaptainHat.PrimalItemSkin_CaptainHat_C'"},
    { "Skin Cat Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_CatMask.PrimalItemSkin_CatMask_C'"},
    { "Skin Chick Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ChickHat.PrimalItemSkin_ChickHat_C'"},
    { "Skin Chili Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ChiliHelmet.PrimalItemSkin_ChiliHelmet_C'"},
    { "Skin Clown Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ClownMask.PrimalItemSkin_ClownMask_C'"},
    { "Skin Devil Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DevilHorns.PrimalItemSkin_DevilHorns_C'"},
    { "Skin Dilo Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DiloMask.PrimalItemSkin_DiloMask_C'"},
    { "Skin Dino Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DinoHat.PrimalItemSkin_DinoHat_C'"},
    { "Skin Dodorex Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DodorexMask.PrimalItemSkin_DodorexMask_C'"},
    { "Skin Dodowyvern Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DodowyvernHat.PrimalItemSkin_DodowyvernHat_C'"},
    { "Skin Dot Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DogMask.PrimalItemSkin_DogMask_C'"},
    { "Skin Explorer Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ExplorerHat.PrimalItemSkin_ExplorerHat_C'"},
    { "Skin GoldCrown Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_GoldCrown.PrimalItemSkin_GoldCrown_C'"},
    { "Skin Halo Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_HaloHat.PrimalItemSkin_HaloHat_C'"},
    { "Skin Manticore Boots", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreBoots.PrimalItemSkin_ManticoreBoots_C'"},
    { "Skin Manticore Gloves", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreGloves.PrimalItemSkin_ManticoreGloves_C'"},
    { "Skin Manticore Helmet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreHelmet.PrimalItemSkin_ManticoreHelmet_C'"},
    { "Skin Manticore Pants", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticorePants.PrimalItemSkin_ManticorePants_C'"},
    { "Skin Manticore Shield", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreShield.PrimalItemSkin_ManticoreShield_C'"},
    { "Skin Manticore Shirt", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreShirt.PrimalItemSkin_ManticoreShirt_C'"},
    { "Skin Party Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_PartyHat.PrimalItemSkin_PartyHat_C'"},
    { "Skin Razer Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_RazerHat.PrimalItemSkin_RazerHat_C'"},
    { "Skin Santa Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_SantaHat.PrimalItemSkin_SantaHat_C'"},
    { "Skin Skull Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_SkullMask.PrimalItemSkin_SkullMask_C'"},
    { "Skin Spinner Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_SpinnerHat.PrimalItemSkin_SpinnerHat_C'"},
    { "Skin Top Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_TopHat.PrimalItemSkin_TopHat_C'"},
    { "Skin Turkey Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_TurkeyHat.PrimalItemSkin_TurkeyHat_C'"},
    { "Skin Vampire Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_VampireEyes.PrimalItemSkin_VampireEyes_C'"},
    { "Skin Werewolf Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_WerewolfHat.PrimalItemSkin_WerewolfHat_C'"},
    { "Skin Witch Hat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_WitchHat.PrimalItemSkin_WitchHat_C'"},
    { "Tek Boots", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/TEK/PrimalItemArmor_TekBoots.PrimalItemArmor_TekBoots_C'"},
    { "Tek Gloves", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/TEK/PrimalItemArmor_TekGloves.PrimalItemArmor_TekGloves_C'"},
    { "Tek Helmet", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/TEK/PrimalItemArmor_TekHelmet.PrimalItemArmor_TekHelmet_C'"},
    { "Tek Pants", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/TEK/PrimalItemArmor_TekPants.PrimalItemArmor_TekPants_C'"},
    { "Tek SCUBA Mask", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/TEK/PrimalItemArmor_TEKScubaHelmet.PrimalItemArmor_TEKScubaHelmet_C'"},
    { "Tek Shirt", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/TEK/PrimalItemArmor_TekShirt.PrimalItemArmor_TekShirt_C'"},
    { "GENERIC Artifact", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifactGeneric.PrimalItemArtifactGeneric_C'"},
    { "Artifact Hunter", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_01.PrimalItemArtifact_01_C'"},
    { "Artifact Pack", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_02.PrimalItemArtifact_02_C'"},
    { "Artifact Massive", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_03.PrimalItemArtifact_03_C'"},
    { "Artifact Devious", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_04.PrimalItemArtifact_04_C'"},
    { "Artifact Clever", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_05.PrimalItemArtifact_05_C'"},
    { "Artifact Skylord", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_06.PrimalItemArtifact_06_C'"},
    { "Artifact Devour", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_07.PrimalItemArtifact_07_C'"},
    { "Artifact Immune", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_08.PrimalItemArtifact_08_C'"},
    { "Artifact Strong", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_09.PrimalItemArtifact_09_C'"},
    { "Artifact 10", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_10.PrimalItemArtifact_C'"},
    { "Artifact Bonus", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItem_Bonus.PrimalItem_Bonus_C'"},
    { "Artifact Bonus2", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItem_Bonus2.PrimalItem_Bonus2_C'"},
    { "Beer Jar", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_BeerJar.PrimalItemConsumable_BeerJar_C'"},
    { "Beer Jar 2", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_BeerJarAlt.PrimalItemConsumable_BeerJarAlt_C'"},
    { "Amarberry", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Amarberry.PrimalItemConsumable_Berry_Amarberry_C'"},
    { "Azulberry", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Azulberry.PrimalItemConsumable_Berry_Azulberry_C'"},
    { "Mejoberry", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Mejoberry.PrimalItemConsumable_Berry_Mejoberry_C'"},
    { "Narcoberry", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Narcoberry.PrimalItemConsumable_Berry_Narcoberry_C'"},
    { "Stimberry", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Stimberry.PrimalItemConsumable_Berry_Stimberry_C'"},
    { "Tintoberry", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Berry_Tintoberry.PrimalItemConsumable_Berry_Tintoberry_C'"},
    { "Blood Pack", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_BloodPack.PrimalItemConsumable_BloodPack_C'"},
    { "Bug Repellant", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_BugRepellant.PrimalItemConsumable_BugRepellant_C'"},
    { "Cactus Soup", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CactusBuffSoup.PrimalItemConsumable_CactusBuffSoup_C'"},
    { "Canteen", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CanteenCraftable.PrimalItemConsumable_CanteenCraftable_C'"},
    { "Cooked Meat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedMeat.PrimalItemConsumable_CookedMeat_C'"},
    { "Cooked Fish Meat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedMeat_Fish.PrimalItemConsumable_CookedMeat_Fish_C'"},
    { "Cooked Meat Jerky", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedMeat_Jerky.PrimalItemConsumable_CookedMeat_Jerky_C'"},
    { "Cooked Prime Meat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedPrimeMeat.PrimalItemConsumable_CookedPrimeMeat_C'"},
    { "Cooked Prime Fish Meat", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedPrimeMeat_Fish.PrimalItemConsumable_CookedPrimeMeat_Fish_C'"},
    { "Cooked Prime Meat Jerky", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_CookedPrimeMeat_Jerky.PrimalItemConsumable_CookedPrimeMeat_Jerky_C'"},
    { "Eery Candy", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_DinoCandy.PrimalItemConsumable_DinoCandy_C'"},
    { "Large Poop", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_DinoPoopLarge.PrimalItemConsumable_DinoPoopLarge_C'"},
    { "Massive Poop", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_DinoPoopMassive.PrimalItemConsumable_DinoPoopMassive_C'"},
    { "Medium Poop", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_DinoPoopMedium.PrimalItemConsumable_DinoPoopMedium_C'"},
    { "Small Poop", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_DinoPoopSmall.PrimalItemConsumable_DinoPoopSmall_C'"},
    { "BASE Dungeon Salve", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_DungeonSalve_Base.PrimalItemConsumable_DungeonSalve_Base_C'"},
    { "Hemostatic Serum", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_DungeonSalve_Healing.PrimalItemConsumable_DungeonSalve_Healing_C'"},
    { "Minor Hemostatic Serum", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_DungeonSalve_Healing_Minor.PrimalItemConsumable_DungeonSalve_Healing_Minor_C'"},
    { "Stamina Serum", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_DungeonSalve_Stamina.PrimalItemConsumable_DungeonSalve_Stamina_C'"},
    { "Dungeon Temperature Serum", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_DungeonSalve_Temperature.PrimalItemConsumable_DungeonSalve_Temperature_C'"},
    { "Dungeon Minor Temperature Serum", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_DungeonSalve_Temperature_Minor.PrimalItemConsumable_DungeonSalve_Temperature_Minor_C'"},
    { "Fertilizer Compost", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Fertilizer_Compost.PrimalItemConsumable_Fertilizer_Compost_C'"},
    { "Frog Legs", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_FrogLegs.PrimalItemConsumable_FrogLegs_C'"},
    { "Medical Brews", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_HealSoup.PrimalItemConsumable_HealSoup_C'"},
    { "Honey", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Honey.PrimalItemConsumable_Honey_C'"},
    { "Human Poop", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_HumanPoop.PrimalItemConsumable_HumanPoop_C'"},
    { "Ice Canteen", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_IcedCanteenRefill.PrimalItemConsumable_IcedCanteenRefill_C'"},
    { "Ice Water Jar", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_IcedWaterJarRefill.PrimalItemConsumable_IcedWaterJarRefill_C'"},
    { "Biotoxin", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_JellyVenom.PrimalItemConsumable_JellyVenom_C'"},
    { "Allo Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Allo.PrimalItemConsumable_Kibble_Allo_C'"},
    { "Anky Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_AnkyloEgg.PrimalItemConsumable_Kibble_AnkyloEgg_C'"},
    { "Archaeoptryx Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_ArchaEgg.PrimalItemConsumable_Kibble_ArchaEgg_C'"},
    { "Argentavis Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_ArgentEgg.PrimalItemConsumable_Kibble_ArgentEgg_C'"},
    { "Baryonyx Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_BaryonyxEgg.PrimalItemConsumable_Kibble_BaryonyxEgg_C'"},
    { "Titanboa Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_BoaEgg.PrimalItemConsumable_Kibble_BoaEgg_C'"},
    { "Carno Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_CarnoEgg.PrimalItemConsumable_Kibble_CarnoEgg_C'"},
    { "Compy Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Compy.PrimalItemConsumable_Kibble_Compy_C'"},
    { "Dilo Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_DiloEgg.PrimalItemConsumable_Kibble_DiloEEgg_C'"},
    { "Dimetro Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_DimetroEgg.PrimalItemConsumable_Kibble_DimetroEgg_C'"},
    { "Dimorph Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_DimorphEgg.PrimalItemConsumable_Kibble_DimorphEgg_C'"},
    { "Diplodocus Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_DiploEgg.PrimalItemConsumable_Kibble_DiploEgg_C'"},
    { "Dodo Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_DodoEgg.PrimalItemConsumable_Kibble_DodoEgg_C'"},
    { "Galli Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_GalliEgg.PrimalItemConsumable_Kibble_GalliEgg_C'"},
    { "Griffin Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_Griffin.PrimalItemConsumable_Kibble_Griffin_C'"},
    { "Iguanadon Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_IguanodonEgg.PrimalItemConsumable_Kibble_IguanodonEgg_C'"},
    { "Kairuku Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_KairukuEgg.PrimalItemConsumable_Kibble_KairukuEgg_C'"},
    { "Kapro Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_KaproEgg.PrimalItemConsumable_Kibble_KaproEgg_C'"},
    { "Lystro Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_LystroEgg.PrimalItemConsumable_Kibble_LystroEgg_C'"},
    { "Megalosaurus Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_MegalosaurusEgg.PrimalItemConsumable_Kibble_MegalosaurusEgg_C'"},
    { "Moschops Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_MoschopsEgg.PrimalItemConsumable_Kibble_MoschopsEgg_C'"},
    { "Oviraptor Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_OviraptorEgg.PrimalItemConsumable_Kibble_OviraptorEgg_C'"},
    { "Pachy Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_PachyEgg.PrimalItemConsumable_Kibble_PachyEgg_C'"},
    { "Pachyrhino Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_PachyRhinoEgg.PrimalItemConsumable_Kibble_PachyRhinoEgg_C'"},
    { "Parasaur Kibble", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Consumables/PrimalItemConsumable_Kibble_ParaEgg.PrimalItemConsumable_Kibble_ParaEgg_C'"},
    { "Bola", L"Blueprint'/Game/PrimalEarth/CoreBlueprints/Weapons/PrimalItem_WeaponBola.PrimalItem_WeaponBola_C'"}
};

std::map<const char*, const wchar_t*> dinoSpawnsAllOther = {
    {"Achatina", L"Achatina_Character_BP_C"},
    {"Allosaurus", L"Allo_Character_BP_C"},
    {"Ammonite", L"Ammonite_Character_C"},
    {"Angler", L"Angler_Character_BP_C"},
    {"Anky", L"Ankylo_Character_BP_C"},
    {"Araneo", L"SpiderS_Character_BP_C"},
    {"Archaeoptryx", L"Archa_Character_BP_C"},
    {"Argentavis", L"Argent_Character_BP_C"},
    {"Arthro", L"Arthro_Character_BP_C"},
    {"Baryonyx", L"Baryonyx_Character_BP_C"},
    {"Basilosaurus", L"Basilosaurus_Character_BP_C"},
    {"Beelzebufo", L"Toad_Character_BP_C"},
    {"Bunny Oviraptor", L"BunnyOviRaptor_Character_BP_C"},
    {"Brontosaurus", L"Sauropod_Character_BP_C"},
    {"Broodmother", L"SpiderL_Character_BP_C"},
    {"Chalicotherium", L"Chalico_Character_BP_C"},
    {"Carbonemys", L"Turtle_Character_BP_C"},
    {"Carnotaurus", L"Carno_Character_BP_C"},
    {"Castoroides", L"Beaver_Character_BP_C"},
    {"Cnidaria", L"Cnidaria_Character_BP_C"},
    {"Coelacanth", L"Coel_Character_BP_C"},
    {"Compy", L"Compy_Character_BP_C"},
    {"Daeoodon", L"Daeodon_Character_BP_C"},
    {"Dilophosaur", L"Dilo_Character_BP_C"},
    {"Dimetrodon", L"Dimetro_Character_BP_C"},
    {"Dimorphodon", L"Dimorph_Character_BP_C"},
    {"Diplocalus", L"Diplocaulus_Character_BP_C"},
    {"Diplodocus", L"Diplodocus_Character_BP_C"},
    {"Direbear", L"Direbear_Character_BP_C"},
    {"Direwolf", L"Direwolf_Character_BP_C"},
    {"Dodo", L"Dodo_Character_BP_C"},
    {"Doedicurus", L"Doed_Character_BP_C"},
    {"Dung Beetle", L"DungBeetle_Character_BP_C"},
    {"Dunkleosteus", L"Dunkle_Character_BP_C"},
    {"Electrophorus", L"Eel_Character_BP_C"},
    {"Equus", L"Equus_Character_BP_C"},
    {"Unicorn", L"Equus_Character_BP_Unicorn_C"},
    {"Eurypterid", L"Euryp_Character_C"},
    {"Gallimimus", L"Galli_Character_BP_C"},
    {"Giganotosaurus", L"Gigant_Character_BP_C"},
    {"Gigantopithecus", L"Bigfoot_Character_BP_C"},
    {"Griffin", L"Griffin_Character_BP_C"},
    {"Ichthyosaurus", L"Dolphin_Character_BP_C"},
    {"Iguanadon", L"Iguanodon_Character_BP_C"},
    {"Jerboa", L"Jerboa_Character_BP_C"},
    {"Kairuku", L"Kairuku_Character_BP_C"},
    {"Kaprosuchus", L"Kaprosuchus_Character_BP_C"},
    {"Leech", L"Leech_Character_C"},
    {"Diseased Leech", L"Leech_Character_Diseased_C"},
    {"Leedsichthys", L"Leedsichthys_Character_BP_C"},
    {"Liopleurodon", L"Liopleurodon_Character_BP_C"},
    {"Lystrosaurus", L"Lystro_Character_BP_C"},
    {"Mammoth", L"Mammoth_Character_BP_C"},
    {"Manta", L"Manta_Character_BP_C"},
    {"Mantis", L"Mantis_Character_BP_C"},
    {"Megalocerus", L"Stag_Character_BP_C"},
    {"Megaladon", L"Megalodon_Character_BP_C"},
    {"Megalosaurus", L"Megalosaurus_Character_BP_C"},
    {"Meganeura", L"Dragonfly_Character_BP_C"},
    {"Megatherium", L"Megatherium_Character_BP_C"},
    {"Mesopithecus", L"Monkey_Character_BP_C"},
    {"Mosasaurus", L"Mosa_Character_BP_C"},
    {"Moschops", L"Moschops_Character_BP_C"},
    {"Onychonycteris", L"Bat_Character_BP_C"},
    {"Otter", L"Otter_Character_BP_C"},
    {"Oviraptor", L"Oviraptor_Character_BP_C"},
    {"Pachy", L"Pachy_Character_BP_C"},
    {"Pachyrhinosaurus", L"Pachyrhino_Character_BP_C"},
    {"Paraceratherium", L"Paracer_Character_BP_C"},
    {"Parasaurolophus", L"Para_Character_BP_C"},
    {"Pegomastax", L"Pegomastax_Character_BP_C"},
    {"Pelagornis", L"Pela_Character_BP_C"},
    {"Phiomia", L"Phiomia_Character_BP_C"},
    {"Piranha", L"Piranha_Character_BP_C"},
    {"Plesiosaur", L"Plesiosaur_Character_BP_C"},
    {"Procoptodon", L"Procoptodon_Character_BP_C"},
    {"Pteranodon", L"Ptero_Character_BP_C"},
    {"Pulmonoscorpius", L"Scorpion_Character_BP_C"},
    {"Purlovia", L"Purlovia_Character_BP_C"},
    {"Quetzalcoatlus", L"Quetz_Character_BP_C"},
    {"Raptor", L"Raptor_Character_BP_C"},
    {"Rex", L"Rex_Character_BP_C"},
    {"Sabertooth", L"Saber_Character_BP_C"},
    {"Sabertooth Salmon", L"Salmon_Character_BP_C"},
    {"Sarco", L"Sarco_Character_BP_C"},
    {"Spino", L"Spino_Character_BP_C"},
    {"Stegosaurus", L"Stego_Character_BP_C"},
    {"Tapejara", L"Tapejara_Character_BP_C"},
    {"Terror Bird", L"TerrorBird_Character_BP_C"},
    {"Therizinosaur", L"Therizino_Character_BP_C"},
    {"Titanboa", L"BoaFrill_Character_BP_C"},
    {"Titanomyrma", L"Ant_Character_BP_C"},
    {"Flying Titanomyrma", L"FlyingAnt_Character_BP_C"},
    {"Titanosaur", L"Titanosaur_Character_BP_C"},
    {"Triceratops", L"Trike_Character_BP_C"},
    {"Trilobite", L"Trilobite_Character_C"},
    {"Troodon", L"Troodon_Character_BP_C"},
    {"Tusoteuthis", L"Tusoteuthis_Character_BP_C"},
    {"Wyvern", L"Wyvern_Character_BP_Base_C"},
    {"Fire Wyvern", L"Wyvern_Character_BP_Fire_C"},
    {"Woolly Rhino", L"Rhino_Character_BP_C"}
};

std::map<const char*, const wchar_t*> specialDinoSpawnsAllOther = {
    {"Zomdodo", L"Blueprint'/Game/PrimalEarth/Dinos/Dodo/ZombieDodo_Character_BP.ZombieDodo_Character_BP_C'"},
    {"BOSS Megapithecus", L"Blueprint'/Game/PrimalEarth/Dinos/Gorilla/Gorilla_Character_BP.Gorilla_Character_BP_C'"},
    {"BOSS Argentustus", L"Blueprint'/Game/PrimalEarth/Dinos/Argentavis/Boss_Argent_Character_BP.Boss_Argent_Character_BP_C'"},
    {"BOSS Obsidioequus", L"Blueprint'/Game/PrimalEarth/Dinos/Chalicotherium/Boss_Chalico_Character_BP.Boss_Chalico_Character_BP_C'"},
    {"BOSS Cubozoa Multis", L"Blueprint'/Game/PrimalEarth/Dinos/Cnidaria/Boss_Cnidaria_Character_BP.Boss_Cnidaria_Character_BP_C'"},
    {"BOSS Dodobitus", L"Blueprint'/Game/PrimalEarth/Dinos/Dodo/Boss_Dodo_Character_BP.Boss_Dodo_Character_BP_C'"},
    {"BOSS Spiderl", L"Blueprint'/Game/PrimalEarth/Dinos/Spider/Boss_Spider_Character_BP.Boss_Spider_Character_BP_C'"},
    {"BOSS Doedicurus Vastus", L"Blueprint'/Game/PrimalEarth/Dinos/Doedicurus/Boss_Doed_Character_BP.Boss_Doed_Character_BP_C'"},
    {"BOSS Gula Beetle", L"Blueprint'/Game/PrimalEarth/Dinos/DungBeetle/Boss_DungBeetle_Character_BP.Boss_DungBeetle_Character_BP_C'"},
    {"BOSS Beelzemorbus", L"Blueprint'/Game/PrimalEarth/Dinos/Toad/Boss_Toad_Character_BP.Boss_Toad_Character_BP_C'"},
    {"Noctis", L"Blueprint'/Game/PrimalEarth/Dinos/Equus/Anticorn_Character_BP.Anticorn_Character_BP_C'"},
    {"Reindeer", L"Blueprint'/Game/PrimalEarth/Dinos/Stag/Reindeer_Character_BP.Reindeer_Character_BP_C'"},
    {"Skeletal Bronto", L"Blueprint'/Game/PrimalEarth/Dinos/Bronto/Bone_Sauropod_Character_BP.Bone_Sauropod_Character_BP_C'"},
    {"Skeletal Carno", L"Blueprint'/Game/PrimalEarth/Dinos/Carno/Bone_MegaCarno_Character_BP.Bone_MegaCarno_Character_BP_C'"},
    {"Skeletal Giganotosaurus", L"Blueprint'/Game/PrimalEarth/Dinos/Giganotosaurus/Bone_Gigant_Character_BP.Bone_Gigant_Character_BP_C'"},
    {"Skeletal Quetzal", L"Blueprint'/Game/PrimalEarth/Dinos/Quetzalcoatlus/Bone_Quetz_Character_BP.Bone_Quetz_Character_BP_C'"},
    {"Skeletal Raptor", L"Blueprint'/Game/PrimalEarth/Dinos/Raptor/Bone_MegaRaptor_Character_BP.Bone_MegaRaptor_Character_BP_C'"},
    {"Skeletal Rex", L"Blueprint'/Game/PrimalEarth/Dinos/Rex/Bone_MegaRex_Character_BP.Bone_MegaRex_Character_BP_C'"},
    {"Skeletal Stego", L"Blueprint'/Game/PrimalEarth/Dinos/Stego/Bone_Stego_Character_BP.Bone_Stego_Character_BP_C'"},
    {"Skeletal Trike", L"Blueprint'/Game/PrimalEarth/Dinos/Trike/Bone_Trike_Character_BP.Bone_Trike_Character_BP_C'"},
    {"Megapithecus", L"Blueprint'/Game/PrimalEarth/Dinos/Gorilla/Gorilla_Character_BP.Gorilla_Character_BP_C'"},
    {"Alpha Carno", L"Blueprint'/Game/PrimalEarth/Dinos/Carno/MegaCarno_Character_BP.MegaCarno_Character_BP_C'"},
    {"Alpha Mosa", L"Blueprint'/Game/PrimalEarth/Dinos/Mosasaurus/Mosa_Character_BP_Mega.Mosa_Character_BP_Mega_C'"},
    {"Alpha Raptor", L"Blueprint'/Game/PrimalEarth/Dinos/Raptor/MegaRaptor_Character_BP.MegaRaptor_Character_BP_C'"},
    {"Alpha Rex", L"Blueprint'/Game/PrimalEarth/Dinos/Rex/MegaRex_Character_BP.MegaRex_Character_BP_C'"},
    {"Yeti", L"Blueprint'/Game/PrimalEarth/Dinos/Bigfoot/Yeti_Character_BP.Yeti_Character_BP_C'"}
};

constexpr const wchar_t kGiveAllSkinsCmd[] = LR"(
cheat admincheat giveslotitem "Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Bark.PrimalItem_ImplantGraft_Bark_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Camo.PrimalItem_ImplantGraft_Camo_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Colorbomb.PrimalItem_ImplantGraft_Colorbomb_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Eerie.PrimalItem_ImplantGraft_Eerie_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Gold.PrimalItem_ImplantGraft_Gold_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Ice.PrimalItem_ImplantGraft_Ice_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Lava.PrimalItem_ImplantGraft_Lava_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Platinum.PrimalItem_ImplantGraft_Platinum_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Stone.PrimalItem_ImplantGraft_Stone_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Warpaint.PrimalItem_ImplantGraft_Warpaint_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/Mobile/SkinGrafts/PrimalItem_ImplantGraft_Yahweh.PrimalItem_ImplantGraft_Yahweh_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemArmor_HunterHat.PrimalItemArmor_HunterHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_Antenna.PrimalItemSkin_Antenna_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_BetaHat.PrimalItemSkin_BetaHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_BrokenEggHat.PrimalItemSkin_BrokenEggHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_BunnyEarsHat.PrimalItemSkin_BunnyEarsHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_CaptainHat.PrimalItemSkin_CaptainHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_CatMask.PrimalItemSkin_CatMask_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ChickHat.PrimalItemSkin_ChickHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ChiliHelmet.PrimalItemSkin_ChiliHelmet_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ClownMask.PrimalItemSkin_ClownMask_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DevilHorns.PrimalItemSkin_DevilHorns_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DiloMask.PrimalItemSkin_DiloMask_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DinoHat.PrimalItemSkin_DinoHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DodorexMask.PrimalItemSkin_DodorexMask_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DodowyvernHat.PrimalItemSkin_DodowyvernHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_DogMask.PrimalItemSkin_DogMask_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ExplorerHat.PrimalItemSkin_ExplorerHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_GoldCrown.PrimalItemSkin_GoldCrown_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_HaloHat.PrimalItemSkin_HaloHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreBoots.PrimalItemSkin_ManticoreBoots_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreGloves.PrimalItemSkin_ManticoreGloves_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreHelmet.PrimalItemSkin_ManticoreHelmet_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticorePants.PrimalItemSkin_ManticorePants_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreShield.PrimalItemSkin_ManticoreShield_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_ManticoreShirt.PrimalItemSkin_ManticoreShirt_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_PartyHat.PrimalItemSkin_PartyHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_RazerHat.PrimalItemSkin_RazerHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_SantaHat.PrimalItemSkin_SantaHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_SkullMask.PrimalItemSkin_SkullMask_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_SpinnerHat.PrimalItemSkin_SpinnerHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_TopHat.PrimalItemSkin_TopHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_TurkeyHat.PrimalItemSkin_TurkeyHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_VampireEyes.PrimalItemSkin_VampireEyes_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_WerewolfHat.PrimalItemSkin_WerewolfHat_C'" 1 1 | admincheat giveslotitem "Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Armor/Skin/PrimalItemSkin_WitchHat.PrimalItemSkin_WitchHat_C'" 1 1
)";
