#include "DinoNames.h"

namespace
{
const bool DinoIndexReady = []
{
    DinoNameDetail::BindIndexRevision();
    return true;
}();
}

std::array<std::wstring, 123> DinoClasses =
{
    L"Achatina_Character_BP_C",
    L"Allo_Character_BP_C",
    L"Angler_Character_BP_C",
    L"Ankylo_Character_BP_C",
    L"Ant_Character_BP_C",
    L"Ant_Character_BP_C",
    L"FlyingAnt_Character_BP_C",
    L"Insect_Character_BP_C",
    L"Archa_Character_BP_C",
    L"Argent_Character_BP_C",
    L"Arthro_Character_BP_C",
    L"Bat_Character_BP_C",
    L"Beaver_Character_BP_C",
    L"Bigfoot_Character_BP_C",
    L"Bigfoot_Character_BP_Aggressive_C",
    L"Yeti_Character_BP_C",
    L"BoaFrill_Character_BP_C",
    L"Bone_MegaCarno_Character_BP_C",
    L"Carno_Character_BP_C",
    L"MegaCarno_Character_BP_C",
    L"Chalico_Character_BP_C",
    L"Coel_Character_BP_C",
    L"Compy_Character_BP_C",
    L"Dilo_Character_BP_C",
    L"Dimetro_Character_BP_C",
    L"Dimorph_Character_BP_C",
    L"Dimorph_Character_BP_Aggressive_C",
    L"Diplocaulus_Character_BP_C",
    L"Diplodocus_Character_BP_C",
    L"Direbear_Character_BP_C",
    L"Direwolf_Character_BP_C",
    L"Dodo_Character_BP_C",
    L"Doed_Character_BP_C",
    L"Dolphin_Character_BP_C",
    L"Dragonfly_Character_BP_C",
    L"DungBeetle_Character_BP_C",
    L"Dunkle_Character_BP_C",
    L"Euryp_Character_C",
    L"Galli_Character_BP_C",
    L"Bone_Gigant_Character_BP_C",
    L"Gigant_Character_BP_C",
    L"Kairuku_Character_BP_C",
    L"Kaprosuchus_Character_BP_C",
    L"Leech_Character_C",
    L"Leech_Character_Diseased_C",
    L"Lystro_Character_BP_C",
    L"Mammoth_Character_BP_C",
    L"Manta_Character_BP_C",
    L"Megalodon_Character_BP_C",
    L"Megalosaurus_Character_BP_C",
    L"Monkey_Character_BP_C",
    L"Monkey_Character_BP_Aggressive_C",
    L"Mosa_Character_BP_C",
    L"Mosa_Character_BP_Mega_C",
    L"Moschops_Character_BP_C",
    L"BunnyOviraptor_Character_BP_C",
    L"Oviraptor_Character_BP_C",
    L"Pachy_Character_BP_C",
    L"Pachyrhino_Character_BP_C",
    L"Para_Character_BP_C",
    L"Paracer_Character_BP_C",
    L"Pegomastax_Character_BP_C",
    L"Pela_Character_BP_C",
    L"Phiomia_Character_BP_C",
    L"Piranha_Character_BP_C",
    L"Plesiosaur_Character_BP_C",
    L"Procoptodon_Character_BP_C",
    L"Ptero_Character_BP_C",
    L"Ptero_Character_BP_Saddle_C",
    L"Ptero_Minion_Character_BP_C",
    L"Bone_Quetz_Character_BP_C",
    L"Quetz_Character_BP_C",
    L"Bone_MegaRaptor_Character_BP_C",
    L"MegaRaptor_Character_BP_C",
    L"Raptor_Character_BP_C",
    L"Raptor_Character_BP_Saddle_C",
    L"Bone_MegaRex_Character_BP_C",
    L"MegaRex_Character_BP_C",
    L"Rex_Character_BP_C",
    L"Rex_Character_BP_Saddled_C",
    L"Saber_Character_BP_C",
    L"Salmon_Character_BP_C",
    L"Sarco_Character_BP_C",
    L"Bone_Sauropod_Character_BP_C",
    L"Sauropod_Character_BP_C",
    L"Sauropod_Character_BP_Saddled_C",
    L"Scorpion_Character_BP_C",
    L"SpiderS_Character_BP_C",
    L"SpiderS_Character_BP_Aggressive_C",
    L"Spino_Character_BP_C",
    L"Reindeer_Character_BP_C",
    L"Stag_Character_BP_C",
    L"Bone_Stego_Character_BP_C",
    L"Stego_Character_BP_C",
    L"Tapejara_Character_BP_C",
    L"TerrorBird_Character_BP_C",
    L"Therizino_Character_BP_C",
    L"Titanosaur_Character_BP_C",
    L"Toad_Character_BP_C",
    L"Bone_Trike_Character_BP_C",
    L"Trike_Character_BP_C",
    L"Trike_Character_BP_Saddle_C",
    L"Trilobite_Character_C",
    L"Troodon_Character_BP_C",
    L"Turtle_Character_BP_C",
    L"Tusoteuthis_Character_BP_C",
    L"Rhino_Character_BP_C",
    L"Cnidaria_Character_BP_C",
    L"Eel_Character_BP_C",
    L"Basilosaurus_Character_BP_C",
    L"Leedsichthys_Character_BP_C",
    L"Ammonite_Character_C",
    L"Liopleurodon_Character_BP_C",
    L"Coel_Character_BP_Ocean_C",
    L"Baryonyx_Character_BP_C",
    L"Iguanodon_Character_BP_C",
    L"Purlovia_Character_BP_C",
    L"Griffin_Character_BP_C",
    L"Otter_Character_BP_C",
    L"Equus_Character_BP_C",
    L"Equus_Character_BP_Unicorn_C",
    L"Megatherium_Character_BP_C",
    L"Jerboa_Character_BP_C"
};

std::map<std::string, std::vector<int>> DinoNameGroups =
{
    { "Achatina",              { 0 } },
    { "Allosaurus",            { 1 } },
    { "Angler",                { 2 } },
    { "Ankylo",                { 3 } },
    { "Ant",                   { 4, 7 } },
    { "Titanomyrma Drone",     { 5 } },
    { "Titanomyrma Soldier",   { 6 } },
    { "Archaeopteryx",         { 8 } },
    { "Argentavis",            { 9 } },
    { "Arthropluera",          { 10 } },
    { "Onyc",                  { 11 } },
    { "Castoroides",           { 12 } },
    { "Gigantopithecus",       { 13, 14 } },
    { "Yeti",                  { 15 } },
    { "Titanoboa",             { 16 } },
    { "Skeletal Carnotaurus",  { 17 } },
    { "Carno",                 { 18 } },
    { "Alpha Carnotaurus",     { 19 } },
    { "Chalicotherium",        { 20 } },
    { "Coelacanth",            { 21 } },
    { "Compy",                 { 22 } },
    { "Dilophosaurus",         { 23 } },
    { "Dimetrodon",            { 24 } },
    { "Dimorphodon",           { 25, 26 } },
    { "Diplocaulus",           { 27 } },
    { "Diplodocus",            { 28 } },
    { "Dire Bear",             { 29 } },
    { "Dire Wolf",             { 30 } },
    { "Dodo",                  { 31 } },
    { "Doedicurus",            { 32 } },
    { "Ichthyosaurus",         { 33 } },
    { "Meganeura",             { 34 } },
    { "Dung Beetle",           { 35 } },
    { "Dunkleosteus",          { 36 } },
    { "Eurypterid",            { 37 } },
    { "Gallimimus",            { 38 } },
    { "Skeletal Giganotosaurus",{ 39 } },
    { "Giganotosaurus",        { 40 } },
    { "Kairuku",               { 41 } },
    { "Kaprosuchus",           { 42 } },
    { "Leech",                 { 43 } },
    { "Diseased Leech",        { 44 } },
    { "Lystrosaurus",          { 45 } },
    { "Mammoth",               { 46 } },
    { "Manta",                 { 47 } },
    { "Megalodon",             { 48 } },
    { "Megalosaurus",          { 49 } },
    { "Mesopithecus",          { 50, 51 } },
    { "Mosasaur",              { 52 } },
    { "Alpha Mosasaur",        { 53 } },
    { "Moschops",              { 54 } },
    { "BunnyOviraptor",        { 55 } },
    { "Oviraptor",             { 56 } },
    { "Pachy",                 { 57 } },
    { "Pachyrhinosaurus",      { 58 } },
    { "Parasaur",              { 59 } },
    { "Paraceratherium",       { 60 } },
    { "Pegomastax",            { 61 } },
    { "Pelagornis",            { 62 } },
    { "Phiomia",               { 63 } },
    { "Megapiranha",           { 64 } },
    { "Plesiosaur",            { 65 } },
    { "Procoptodon",           { 66 } },
    { "Pteranodon",            { 67, 68, 69 } },
    { "Skeletal Quetzal",      { 70 } },
    { "Quetzal",               { 71 } },
    { "Skeletal Raptor",       { 72 } },
    { "Alpha Raptor",          { 73 } },
    { "Raptor",                { 74 } },
    { "Utahraptor",            { 75 } },
    { "Skeletal Rex",          { 76 } },
    { "Alpha T-Rex",           { 77 } },
    { "Rex",                   { 78, 79 } },
    { "Sabertooth",            { 80 } },
    { "Sabertooth Salmon",     { 81 } },
    { "Sarco",                 { 82 } },
    { "Skeletal Bronto",       { 83 } },
    { "Bronto",                { 84, 85 } },
    { "Pulmonoscorpius",       { 86 } },
    { "Araneo",                { 87, 88 } },
    { "Spino",                 { 89 } },
    { "Reindeer",              { 90 } },
    { "Megaloceros",           { 91 } },
    { "Skeletal Stego",        { 92 } },
    { "Stego",                 { 93 } },
    { "Tapejara",              { 94 } },
    { "Terror Bird",           { 95 } },
    { "Therizinosaur",         { 96 } },
    { "Titanosaur",            { 97 } },
    { "Beelzebufo",            { 98 } },
    { "Skeletal Trike",        { 99 } },
    { "Triceratops",           { 100, 101 } },
    { "Trilobite",             { 102 } },
    { "Troodon",               { 103 } },
    { "Carbonemys",            { 104 } },
    { "Tusoteuthis",           { 105 } },
    { "Woolly Rhinoceros",     { 106 } },
    { "Cnidaria",              { 107 } },
    { "Electrophorus",         { 108 } },
    { "Basilosaurus",          { 109 } },
    { "Leedsichthys",          { 110 } },
    { "Ammonite",              { 111 } },
    { "Liopleurodon",          { 112 } },
    { "Coelacanth",            { 113 } },
    { "Baryonyx",              { 114 } },
    { "Iguanodon",             { 115 } },
    { "Purlovia",              { 116 } },
    { "Griffin",               { 117 } },
    { "Otter",                 { 118 } },
    { "Equus",                 { 119 } },
    { "Unicorn",               { 120 } },
    { "Megatherium",           { 121 } },
    { "Jerboa",                { 122 } }
};
