#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IslandWaterPlane_Lakes

#include "Basic.hpp"

#include "BP_IslandWaterPlane_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_IslandWaterPlane_Lakes.BP_IslandWaterPlane_Lakes_C
// 0x0000 (0x0628 - 0x0628)
class ABP_IslandWaterPlane_Lakes_C final : public ABP_IslandWaterPlane_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_IslandWaterPlane_Lakes_C">();
	}
	static class ABP_IslandWaterPlane_Lakes_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_IslandWaterPlane_Lakes_C>();
	}
};

}

