#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPHarvestResourceMultiplier

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct BPHarvestResourceMultiplier.BPHarvestResourceMultiplier
// 0x0010 (0x0010 - 0x0000)
struct FBPHarvestResourceMultiplier final
{
public:
	class UClass*                                 ItemType_13_5FCB3BBE40D81BD655C8F1AF3EAFE518;      // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         WeightPerLevelMultiplier_7_CBF4E43549210FC676CD9FBC0CC43571; // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         AddedValuePerLevelMultiplier_11_E472E23E418CB0A0692E6A8508F3BF50; // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

