#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ceiling_Base

#include "Basic.hpp"

#include "StructureBaseBP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ceiling_Base.Ceiling_Base_C
// 0x0000 (0x0BF0 - 0x0BF0)
class ACeiling_Base_C : public AStructureBaseBP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ceiling_Base_C">();
	}
	static class ACeiling_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACeiling_Base_C>();
	}
};

}

