#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Coel_Character_BP_Ocean

#include "Basic.hpp"

#include "Coel_Character_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Coel_Character_BP_Ocean.Coel_Character_BP_Ocean_C
// 0x0000 (0x22C0 - 0x22C0)
class ACoel_Character_BP_Ocean_C final : public ACoel_Character_BP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Coel_Character_BP_Ocean_C">();
	}
	static class ACoel_Character_BP_Ocean_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACoel_Character_BP_Ocean_C>();
	}
};

}

