#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CraftingRequirementsEntry

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CraftingRequirementsEntry.CraftingRequirementsEntry_C
// 0x0018 (0x02E8 - 0x02D0)
class UCraftingRequirementsEntry_C final : public UUserWidget
{
public:
	class UImage*                                 ItemImage;                                         // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ItemName;                                          // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ItemQuantity;                                      // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Setup(const class FString& Param_ItemName, class UTexture2D* Param_ItemImage, int32 Param_ItemQuantity, bool HasRequirements, int32 ItemQuantityOwned);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CraftingRequirementsEntry_C">();
	}
	static class UCraftingRequirementsEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCraftingRequirementsEntry_C>();
	}
};

}

