#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DataListEntryWidgetGenericDisplayString

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass DataListEntryWidgetGenericDisplayString.DataListEntryWidgetGenericDisplayString_C
// 0x0010 (0x03E8 - 0x03D8)
class UDataListEntryWidgetGenericDisplayString_C final : public UDataListEntryWidget
{
public:
	uint8                                         Pad_3D8[0x8];                                      // 0x03D8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UDataListEntryButton*                   MyDataListButton;                                  // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DataListEntryWidgetGenericDisplayString_C">();
	}
	static class UDataListEntryWidgetGenericDisplayString_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDataListEntryWidgetGenericDisplayString_C>();
	}
};

}

