#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DataListEntryWidgetPrimalPremiumItem

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function DataListEntryWidgetPrimalPremiumItem.DataListEntryWidgetPrimalPremiumItem_C.ExecuteUbergraph_DataListEntryWidgetPrimalPremiumItem
// 0x0080 (0x0080 - 0x0000)
struct DataListEntryWidgetPrimalPremiumItem_C_ExecuteUbergraph_DataListEntryWidgetPrimalPremiumItem final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const class FString& ToText)>  K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(bool ShowLock)>                K2Node_CreateDelegate_OutputDelegate2;             // 0x0018(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable2;                               // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B[0x5];                                       // 0x002B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UTexture2D* Texture)>    K2Node_CreateDelegate_OutputDelegate3;             // 0x0030(0x0010)(ZeroConstructor, NoDestructor)
	class FString                                 K2Node_CustomEvent_ToText;                         // 0x0040(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0050(0x0018)()
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_showLock;                       // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6A[0x6];                                       // 0x006A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             K2Node_CustomEvent_texture;                        // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function DataListEntryWidgetPrimalPremiumItem.DataListEntryWidgetPrimalPremiumItem_C.CustomEvent_0
// 0x0008 (0x0008 - 0x0000)
struct DataListEntryWidgetPrimalPremiumItem_C_CustomEvent_0 final
{
public:
	class UTexture2D*                             Texture;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function DataListEntryWidgetPrimalPremiumItem.DataListEntryWidgetPrimalPremiumItem_C.SetPremiumLock
// 0x0001 (0x0001 - 0x0000)
struct DataListEntryWidgetPrimalPremiumItem_C_SetPremiumLock final
{
public:
	bool                                          ShowLock;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function DataListEntryWidgetPrimalPremiumItem.DataListEntryWidgetPrimalPremiumItem_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct DataListEntryWidgetPrimalPremiumItem_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function DataListEntryWidgetPrimalPremiumItem.DataListEntryWidgetPrimalPremiumItem_C.SetPremiumText
// 0x0010 (0x0010 - 0x0000)
struct DataListEntryWidgetPrimalPremiumItem_C_SetPremiumText final
{
public:
	class FString                                 ToText;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};

}

