#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DayCycleManager_TheIsland

#include "Basic.hpp"

#include "DayCycleManagerBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DayCycleManager_TheIsland.DayCycleManager_TheIsland_C
// 0x0000 (0x0748 - 0x0748)
class ADayCycleManager_TheIsland_C final : public ADayCycleManagerBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DayCycleManager_TheIsland_C">();
	}
	static class ADayCycleManager_TheIsland_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADayCycleManager_TheIsland_C>();
	}
};

}

