#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DayCycleManagerBase

#include "Basic.hpp"


namespace SDK::Params
{

// Function DayCycleManagerBase.DayCycleManagerBase_C.ActivatedStructureUpdated
// 0x0008 (0x0008 - 0x0000)
struct DayCycleManagerBase_C_ActivatedStructureUpdated final
{
public:
	class APrimalStructureItemContainer*          ActiveStructure;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function DayCycleManagerBase.DayCycleManagerBase_C.GetWeatherEventWarning
// 0x0004 (0x0004 - 0x0000)
struct DayCycleManagerBase_C_GetWeatherEventWarning final
{
public:
	int32                                         WeatherEventWarningType;                           // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

