#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DestroyedMeshBase_IgnoreSelf_FastFade

#include "Basic.hpp"

#include "DestroyedMeshBase_IgnoreSelf_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DestroyedMeshBase_IgnoreSelf_FastFade.DestroyedMeshBase_IgnoreSelf_FastFade_C
// 0x0000 (0x0610 - 0x0610)
class ADestroyedMeshBase_IgnoreSelf_FastFade_C final : public ADestroyedMeshBase_IgnoreSelf_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DestroyedMeshBase_IgnoreSelf_FastFade_C">();
	}
	static class ADestroyedMeshBase_IgnoreSelf_FastFade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADestroyedMeshBase_IgnoreSelf_FastFade_C>();
	}
};

}

