#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DiloSpit_TrailEmitter

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DiloSpit_TrailEmitter.DiloSpit_TrailEmitter_C
// 0x0008 (0x06A0 - 0x0698)
class ADiloSpit_TrailEmitter_C final : public APrimalEmitterSpawnable
{
public:
	uint8                                         Pad_698[0x8];                                      // 0x0698(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DiloSpit_TrailEmitter_C">();
	}
	static class ADiloSpit_TrailEmitter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADiloSpit_TrailEmitter_C>();
	}
};

}

