#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Dilo_AIController_BP

#include "Basic.hpp"

#include "Dino_AIController_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Dilo_AIController_BP.Dilo_AIController_BP_C
// 0x0000 (0x0A68 - 0x0A68)
class ADilo_AIController_BP_C final : public ADino_AIController_BP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Dilo_AIController_BP_C">();
	}
	static class ADilo_AIController_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADilo_AIController_BP_C>();
	}
};

}

