#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoSettings_Carnivore_Medium

#include "Basic.hpp"

#include "DinoSettings_Carnivore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DinoSettings_Carnivore_Medium.DinoSettings_Carnivore_Medium_C
// 0x0000 (0x0090 - 0x0090)
class UDinoSettings_Carnivore_Medium_C : public UDinoSettings_Carnivore_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DinoSettings_Carnivore_Medium_C">();
	}
	static class UDinoSettings_Carnivore_Medium_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDinoSettings_Carnivore_Medium_C>();
	}
};

}

