

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoListEntry

#include "Basic.hpp"

#include "DinoListEntry_classes.hpp"
#include "DinoListEntry_parameters.hpp"


namespace SDK
{

// Function DinoListEntry.DinoListEntry_C.ExecuteUbergraph_DinoListEntry
// ()
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDinoListEntry_C::ExecuteUbergraph_DinoListEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DinoListEntry_C", "ExecuteUbergraph_DinoListEntry");

	Params::DinoListEntry_C_ExecuteUbergraph_DinoListEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DinoListEntry.DinoListEntry_C.BndEvt__MainButton_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UDinoListEntry_C::BndEvt__MainButton_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DinoListEntry_C", "BndEvt__MainButton_K2Node_ComponentBoundEvent_15_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DinoListEntry.DinoListEntry_C.Init
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FTamedDinoEntry                  DinoEntry                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// class UUI_TamedDinoPopUp*               OwningUI                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UDinoListEntry_C::Init(const struct FTamedDinoEntry& DinoEntry, class UUI_TamedDinoPopUp* OwningUI)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DinoListEntry_C", "Init");

	Params::DinoListEntry_C_Init Parms{};

	Parms.DinoEntry = std::move(DinoEntry);
	Parms.OwningUI = OwningUI;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DinoListEntry.DinoListEntry_C.SetSelected
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Selected                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UDinoListEntry_C::SetSelected(bool Selected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DinoListEntry_C", "SetSelected");

	Params::DinoListEntry_C_SetSelected Parms{};

	Parms.Selected = Selected;

	UObject::ProcessEvent(Func, &Parms);
}

}

