#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoSpawnEntriesRedwoods

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DinoSpawnEntriesRedwoods.DinoSpawnEntriesRedwoods_C
// 0x0000 (0x0050 - 0x0050)
class UDinoSpawnEntriesRedwoods_C final : public UNPCSpawnEntriesContainer
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DinoSpawnEntriesRedwoods_C">();
	}
	static class UDinoSpawnEntriesRedwoods_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDinoSpawnEntriesRedwoods_C>();
	}
};

}

