#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoSpawnEntriesTitano

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DinoSpawnEntriesTitano.DinoSpawnEntriesTitano_C
// 0x0000 (0x0050 - 0x0050)
class UDinoSpawnEntriesTitano_C final : public UNPCSpawnEntriesContainer
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DinoSpawnEntriesTitano_C">();
	}
	static class UDinoSpawnEntriesTitano_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDinoSpawnEntriesTitano_C>();
	}
};

}

