#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoEntry_Sarco

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DinoEntry_Sarco.DinoEntry_Sarco_C
// 0x0000 (0x0080 - 0x0080)
class UDinoEntry_Sarco_C final : public UPrimalDinoEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DinoEntry_Sarco_C">();
	}
	static class UDinoEntry_Sarco_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDinoEntry_Sarco_C>();
	}
};

}

