#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoSpawnEntriesCave5

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DinoSpawnEntriesCave5.DinoSpawnEntriesCave5_C
// 0x0000 (0x0050 - 0x0050)
class UDinoSpawnEntriesCave5_C final : public UNPCSpawnEntriesContainer
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DinoSpawnEntriesCave5_C">();
	}
	static class UDinoSpawnEntriesCave5_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDinoSpawnEntriesCave5_C>();
	}
};

}

