#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoSpawnEntries_DarkWater_Lio

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DinoSpawnEntries_DarkWater_Lio.DinoSpawnEntries_DarkWater_Lio_C
// 0x0000 (0x0050 - 0x0050)
class UDinoSpawnEntries_DarkWater_Lio_C final : public UNPCSpawnEntriesContainer
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DinoSpawnEntries_DarkWater_Lio_C">();
	}
	static class UDinoSpawnEntries_DarkWater_Lio_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDinoSpawnEntries_DarkWater_Lio_C>();
	}
};

}

