#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoSpawnEntriesMonsterIsland

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DinoSpawnEntriesMonsterIsland.DinoSpawnEntriesMonsterIsland_C
// 0x0000 (0x0050 - 0x0050)
class UDinoSpawnEntriesMonsterIsland_C final : public UNPCSpawnEntriesContainer
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DinoSpawnEntriesMonsterIsland_C">();
	}
	static class UDinoSpawnEntriesMonsterIsland_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDinoSpawnEntriesMonsterIsland_C>();
	}
};

}

