#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoEntry_Kaprosuchus

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DinoEntry_Kaprosuchus.DinoEntry_Kaprosuchus_C
// 0x0000 (0x0080 - 0x0080)
class UDinoEntry_Kaprosuchus_C final : public UPrimalDinoEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DinoEntry_Kaprosuchus_C">();
	}
	static class UDinoEntry_Kaprosuchus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDinoEntry_Kaprosuchus_C>();
	}
};

}

