#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoEntry_Coel

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DinoEntry_Coel.DinoEntry_Coel_C
// 0x0000 (0x0080 - 0x0080)
class UDinoEntry_Coel_C final : public UPrimalDinoEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DinoEntry_Coel_C">();
	}
	static class UDinoEntry_Coel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDinoEntry_Coel_C>();
	}
};

}

