#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DmgType_Melee_BaseHatchet

#include "Basic.hpp"

#include "DmgType_Melee_HarvestWeapon_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DmgType_Melee_BaseHatchet.DmgType_Melee_BaseHatchet_C
// 0x0000 (0x0140 - 0x0140)
class UDmgType_Melee_BaseHatchet_C : public UDmgType_Melee_HarvestWeapon_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DmgType_Melee_BaseHatchet_C">();
	}
	static class UDmgType_Melee_BaseHatchet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDmgType_Melee_BaseHatchet_C>();
	}
};

}

