

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DroppedItemGenericLowQuality

#include "Basic.hpp"

#include "DroppedItemGenericLowQuality_classes.hpp"


namespace SDK
{

// Function DroppedItemGenericLowQuality.DroppedItemGenericLowQuality_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ADroppedItemGenericLowQuality_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DroppedItemGenericLowQuality_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

