#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EngramEntry_Cannon

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EngramEntry_Cannon.EngramEntry_Cannon_C
// 0x0000 (0x00F8 - 0x00F8)
class UEngramEntry_Cannon_C final : public UPrimalEngramEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EngramEntry_Cannon_C">();
	}
	static class UEngramEntry_Cannon_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEngramEntry_Cannon_C>();
	}
};

}

