#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EngramEntry_SimpleRifle

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EngramEntry_SimpleRifle.EngramEntry_SimpleRifle_C
// 0x0000 (0x00F8 - 0x00F8)
class UEngramEntry_SimpleRifle_C final : public UPrimalEngramEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EngramEntry_SimpleRifle_C">();
	}
	static class UEngramEntry_SimpleRifle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEngramEntry_SimpleRifle_C>();
	}
};

}

