#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EngramEntry_HideHelmet

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EngramEntry_HideHelmet.EngramEntry_HideHelmet_C
// 0x0000 (0x00F8 - 0x00F8)
class UEngramEntry_HideHelmet_C final : public UPrimalEngramEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EngramEntry_HideHelmet_C">();
	}
	static class UEngramEntry_HideHelmet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEngramEntry_HideHelmet_C>();
	}
};

}

