#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EngramEntry_StoneClub

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EngramEntry_StoneClub.EngramEntry_StoneClub_C
// 0x0000 (0x00F8 - 0x00F8)
class UEngramEntry_StoneClub_C final : public UPrimalEngramEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EngramEntry_StoneClub_C">();
	}
	static class UEngramEntry_StoneClub_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEngramEntry_StoneClub_C>();
	}
};

}

