#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EngramEntry_WoodWallWithDoor

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EngramEntry_WoodWallWithDoor.EngramEntry_WoodWallWithDoor_C
// 0x0000 (0x00F8 - 0x00F8)
class UEngramEntry_WoodWallWithDoor_C final : public UPrimalEngramEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EngramEntry_WoodWallWithDoor_C">();
	}
	static class UEngramEntry_WoodWallWithDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEngramEntry_WoodWallWithDoor_C>();
	}
};

}

