#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EngramEntry_StoneWall

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EngramEntry_StoneWall.EngramEntry_StoneWall_C
// 0x0000 (0x00F8 - 0x00F8)
class UEngramEntry_StoneWall_C final : public UPrimalEngramEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EngramEntry_StoneWall_C">();
	}
	static class UEngramEntry_StoneWall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEngramEntry_StoneWall_C>();
	}
};

}

