#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EngramEntry_ChitinPants

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EngramEntry_ChitinPants.EngramEntry_ChitinPants_C
// 0x0000 (0x00F8 - 0x00F8)
class UEngramEntry_ChitinPants_C final : public UPrimalEngramEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EngramEntry_ChitinPants_C">();
	}
	static class UEngramEntry_ChitinPants_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEngramEntry_ChitinPants_C>();
	}
};

}

