#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EngramEntry_Saddle_Therizino

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass EngramEntry_Saddle_Therizino.EngramEntry_Saddle_Therizino_C
// 0x0000 (0x00F8 - 0x00F8)
class UEngramEntry_Saddle_Therizino_C final : public UPrimalEngramEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EngramEntry_Saddle_Therizino_C">();
	}
	static class UEngramEntry_Saddle_Therizino_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEngramEntry_Saddle_Therizino_C>();
	}
};

}

