#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ForceSuccess_TK

#include "Basic.hpp"

#include "AIModule_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass ForceSuccess_TK.ForceSuccess_TK_C
// 0x0008 (0x00A8 - 0x00A0)
class UForceSuccess_TK_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A0(0x0008)(Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_ForceSuccess_TK(int32 EntryPoint);
	void ReceiveExecute(class AActor* OwnerActor);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ForceSuccess_TK_C">();
	}
	static class UForceSuccess_TK_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UForceSuccess_TK_C>();
	}
};

}

