#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GenericOptionWidget

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass GenericOptionWidget.GenericOptionWidget_C
// 0x0000 (0x02D0 - 0x02D0)
class UGenericOptionWidget_C : public UUserWidget
{
public:
	void ApplyOption(class UUI_GenericOptions* WithOptionUI);
	void SetupWithOption(class UGenericOptionsMenu_C* WithOptionUI, const struct FGenericOption& OptionStruct);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GenericOptionWidget_C">();
	}
	static class UGenericOptionWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGenericOptionWidget_C>();
	}
};

}

