#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HalloweenDropper_TheIsland

#include "Basic.hpp"

#include "HalloweenDropper_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HalloweenDropper_TheIsland.HalloweenDropper_TheIsland_C
// 0x0000 (0x0670 - 0x0670)
class AHalloweenDropper_TheIsland_C final : public AHalloweenDropper_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HalloweenDropper_TheIsland_C">();
	}
	static class AHalloweenDropper_TheIsland_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHalloweenDropper_TheIsland_C>();
	}
};

}

