#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IsFlyingBool

#include "Basic.hpp"

#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass IsFlyingBool.IsFlyingBool_C
// 0x0000 (0x0098 - 0x0098)
class UIsFlyingBool_C final : public UBTDecorator_BlueprintBase
{
public:
	bool PerformConditionCheckAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"IsFlyingBool_C">();
	}
	static class UIsFlyingBool_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UIsFlyingBool_C>();
	}
};

}

