

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IsNotPlayerMoveCommand_DK

#include "Basic.hpp"

#include "IsNotPlayerMoveCommand_DK_classes.hpp"
#include "IsNotPlayerMoveCommand_DK_parameters.hpp"


namespace SDK
{

// Function IsNotPlayerMoveCommand_DK.IsNotPlayerMoveCommand_DK_C.PerformConditionCheck
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           OwnerActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UIsNotPlayerMoveCommand_DK_C::PerformConditionCheck(class AActor* OwnerActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("IsNotPlayerMoveCommand_DK_C", "PerformConditionCheck");

	Params::IsNotPlayerMoveCommand_DK_C_PerformConditionCheck Parms{};

	Parms.OwnerActor = OwnerActor;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

