

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LevelUpPanel

#include "Basic.hpp"

#include "LevelUpPanel_classes.hpp"
#include "LevelUpPanel_parameters.hpp"


namespace SDK
{

// Function LevelUpPanel.LevelUpPanel_C.ExecuteUbergraph_LevelUpPanel
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULevelUpPanel_C::ExecuteUbergraph_LevelUpPanel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LevelUpPanel_C", "ExecuteUbergraph_LevelUpPanel");

	Params::LevelUpPanel_C_ExecuteUbergraph_LevelUpPanel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LevelUpPanel.LevelUpPanel_C.BndEvt__ApplyLevelsButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void ULevelUpPanel_C::BndEvt__ApplyLevelsButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LevelUpPanel_C", "BndEvt__ApplyLevelsButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LevelUpPanel.LevelUpPanel_C.BndEvt__CancelButton_K2Node_ComponentBoundEvent_57_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void ULevelUpPanel_C::BndEvt__CancelButton_K2Node_ComponentBoundEvent_57_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LevelUpPanel_C", "BndEvt__CancelButton_K2Node_ComponentBoundEvent_57_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LevelUpPanel.LevelUpPanel_C.BndEvt__BackgroundButton_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void ULevelUpPanel_C::BndEvt__BackgroundButton_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LevelUpPanel_C", "BndEvt__BackgroundButton_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LevelUpPanel.LevelUpPanel_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULevelUpPanel_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LevelUpPanel_C", "Tick");

	Params::LevelUpPanel_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LevelUpPanel.LevelUpPanel_C.Init
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUI_Inventory*                    Inventory_Menu                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimalCharacterStatusComponent*  ForCharacter                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULevelUpPanel_C::Init(class UUI_Inventory* Inventory_Menu, class UPrimalCharacterStatusComponent* ForCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LevelUpPanel_C", "Init");

	Params::LevelUpPanel_C_Init Parms{};

	Parms.Inventory_Menu = Inventory_Menu;
	Parms.ForCharacter = ForCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LevelUpPanel.LevelUpPanel_C.SetUpButtons
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimalCharacterStatusComponent*  ForCharacter                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULevelUpPanel_C::SetUpButtons(class UPrimalCharacterStatusComponent* ForCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LevelUpPanel_C", "SetUpButtons");

	Params::LevelUpPanel_C_SetUpButtons Parms{};

	Parms.ForCharacter = ForCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LevelUpPanel.LevelUpPanel_C.GetNumLevelsToApply
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   OutLevels                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULevelUpPanel_C::GetNumLevelsToApply(int32* OutLevels)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LevelUpPanel_C", "GetNumLevelsToApply");

	Params::LevelUpPanel_C_GetNumLevelsToApply Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutLevels != nullptr)
		*OutLevels = Parms.OutLevels;
}


// Function LevelUpPanel.LevelUpPanel_C.ShowLevelUpStat
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPrimalCharacterStatusValue             Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULevelUpPanel_C::ShowLevelUpStat(EPrimalCharacterStatusValue Type)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LevelUpPanel_C", "ShowLevelUpStat");

	Params::LevelUpPanel_C_ShowLevelUpStat Parms{};

	Parms.Type = Type;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LevelUpPanel.LevelUpPanel_C.GetButtonForType
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPrimalCharacterStatusValue             Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ULevelUpEntry_C*                  Entry                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULevelUpPanel_C::GetButtonForType(EPrimalCharacterStatusValue Type, class ULevelUpEntry_C** Entry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LevelUpPanel_C", "GetButtonForType");

	Params::LevelUpPanel_C_GetButtonForType Parms{};

	Parms.Type = Type;

	UObject::ProcessEvent(Func, &Parms);

	if (Entry != nullptr)
		*Entry = Parms.Entry;
}


// Function LevelUpPanel.LevelUpPanel_C.UpdateButtons
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DetlaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULevelUpPanel_C::UpdateButtons(float DetlaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LevelUpPanel_C", "UpdateButtons");

	Params::LevelUpPanel_C_UpdateButtons Parms{};

	Parms.DetlaTime = DetlaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LevelUpPanel.LevelUpPanel_C.GetPotentialStatChanges
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FText>                     OutText                                                (Parm, OutParm, ZeroConstructor)

void ULevelUpPanel_C::GetPotentialStatChanges(TArray<class FText>* OutText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LevelUpPanel_C", "GetPotentialStatChanges");

	Params::LevelUpPanel_C_GetPotentialStatChanges Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutText != nullptr)
		*OutText = std::move(Parms.OutText);
}


// Function LevelUpPanel.LevelUpPanel_C.PlayLevelUpSound
// (Public, BlueprintCallable, BlueprintEvent)

void ULevelUpPanel_C::PlayLevelUpSound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LevelUpPanel_C", "PlayLevelUpSound");

	UObject::ProcessEvent(Func, nullptr);
}

}

