#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Lystro_Character_BP

#include "Basic.hpp"

#include "Dino_Character_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Lystro_Character_BP.Lystro_Character_BP_C
// 0x0030 (0x22F0 - 0x22C0)
class ALystro_Character_BP_C final : public ADino_Character_BP_C
{
public:
	class UDinoCharacterStatusComponent_BP_Lystro_C* DinoCharacterStatus_BP_Lystro_C1;                  // 0x22B8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class UAnimMontage*>                   PetAnims;                                          // 0x22C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)
	TSoftClassPtr<class UClass>                   LystroXPBuff;                                      // 0x22D0(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)

public:
	bool BPTryMultiUse(class APlayerController* ForPC, int32 UseIndex);
	void Has_XPBuff(bool* Result);
	TArray<struct FMultiUseEntry> BPGetMultiUseEntries(class APlayerController* ForPC, TArray<struct FMultiUseEntry>& MultiUseEntries);
	void UserConstructionScript();

	struct FLinearColor GetEeryMaterialParams() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Lystro_Character_BP_C">();
	}
	static class ALystro_Character_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALystro_Character_BP_C>();
	}
};

}

