#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MoschopsTamingFoodList

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MoschopsTamingFoodList.MoschopsTamingFoodList_C
// 0x0010 (0x0038 - 0x0028)
class UMoschopsTamingFoodList_C final : public UObject
{
public:
	TArray<class UClass*>                         TamingFoodsList;                                   // 0x0028(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MoschopsTamingFoodList_C">();
	}
	static class UMoschopsTamingFoodList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMoschopsTamingFoodList_C>();
	}
};

}

