#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MultiTapActionMappings

#include "Basic.hpp"


namespace SDK::Params
{

// Function MultiTapActionMappings.MultiTapActionMappings_C.ExecuteUbergraph_MultiTapActionMappings
// 0x0008 (0x0008 - 0x0000)
struct MultiTapActionMappings_C_ExecuteUbergraph_MultiTapActionMappings final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsBuildRelease_ReturnValue;               // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

}

