#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Niagara

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"
#include "Niagara_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class Niagara.NiagaraEffectRendererProperties
// 0x0000 (0x0028 - 0x0028)
class UNiagaraEffectRendererProperties : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraEffectRendererProperties">();
	}
	static class UNiagaraEffectRendererProperties* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraEffectRendererProperties>();
	}
};

// Class Niagara.NiagaraSpriteRendererProperties
// 0x0020 (0x0048 - 0x0028)
class UNiagaraSpriteRendererProperties final : public UNiagaraEffectRendererProperties
{
public:
	struct FVector2D                              SubImageSize;                                      // 0x0028(0x0008)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ENiagaraSpriteAlignment                       Alignment;                                         // 0x0030(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ENiagaraSpriteFacingMode                      FacingMode;                                        // 0x0031(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_32[0x2];                                       // 0x0032(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CustomFacingVectorMask;                            // 0x0034(0x000C)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ENiagaraSortMode                              SortMode;                                          // 0x0040(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraSpriteRendererProperties">();
	}
	static class UNiagaraSpriteRendererProperties* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraSpriteRendererProperties>();
	}
};

// Class Niagara.NiagaraSettings
// 0x0050 (0x0088 - 0x0038)
class UNiagaraSettings final : public UDeveloperSettings
{
public:
	struct FStringAssetReference                  DefaultEffect;                                     // 0x0038(0x0010)(Edit, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FStringAssetReference                  DefaultEmitter;                                    // 0x0048(0x0010)(Edit, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FStringAssetReference                  DefaultScript;                                     // 0x0058(0x0010)(Edit, Config, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FStringAssetReference>          AdditionalParameterTypes;                          // 0x0068(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)
	TArray<struct FStringAssetReference>          AdditionalPayloadTypes;                            // 0x0078(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraSettings">();
	}
	static class UNiagaraSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraSettings>();
	}
};

// Class Niagara.NiagaraScriptSourceBase
// 0x0020 (0x0048 - 0x0028)
class UNiagaraScriptSourceBase final : public UObject
{
public:
	uint8                                         Pad_28[0x20];                                      // 0x0028(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraScriptSourceBase">();
	}
	static class UNiagaraScriptSourceBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraScriptSourceBase>();
	}
};

// Class Niagara.NiagaraScript
// 0x00C0 (0x00E8 - 0x0028)
class UNiagaraScript final : public UObject
{
public:
	TArray<uint8>                                 ByteCode;                                          // 0x0028(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	struct FNiagaraParameters                     Parameters;                                        // 0x0038(0x0010)(NativeAccessSpecifierPublic)
	struct FNiagaraParameters                     InternalParameters;                                // 0x0048(0x0010)(NativeAccessSpecifierPublic)
	TArray<struct FNiagaraVariable>               Attributes;                                        // 0x0058(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FNiagaraDataSetProperties>      EventReceivers;                                    // 0x0068(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FNiagaraDataSetProperties>      EventGenerators;                                   // 0x0078(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	struct FNiagaraScriptDataUsageInfo            DataUsage;                                         // 0x0088(0x0001)(NoDestructor, NativeAccessSpecifierPublic)
	ENiagaraScriptUsage                           Usage;                                             // 0x0089(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, AssetRegistrySearchable, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8A[0x6];                                       // 0x008A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FNiagaraScriptDataInterfaceInfo> DataInterfaceInfo;                                 // 0x0090(0x0010)(ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	TArray<struct FVMExternalFunctionBindingInfo> CalledVMExternalFunctions;                         // 0x00A0(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	ENiagaraNumericOutputTypeSelectionMode        NumericOutputTypeSelectionMode;                    // 0x00B0(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B1[0x27];                                      // 0x00B1(0x0027)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FNiagaraStatScope>              StatScopes;                                        // 0x00D8(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraScript">();
	}
	static class UNiagaraScript* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraScript>();
	}
};

// Class Niagara.NiagaraRibbonRendererProperties
// 0x0000 (0x0028 - 0x0028)
class UNiagaraRibbonRendererProperties final : public UNiagaraEffectRendererProperties
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraRibbonRendererProperties">();
	}
	static class UNiagaraRibbonRendererProperties* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraRibbonRendererProperties>();
	}
};

// Class Niagara.NiagaraMeshRendererProperties
// 0x0008 (0x0030 - 0x0028)
class UNiagaraMeshRendererProperties final : public UNiagaraEffectRendererProperties
{
public:
	class UStaticMesh*                            ParticleMesh;                                      // 0x0028(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraMeshRendererProperties">();
	}
	static class UNiagaraMeshRendererProperties* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraMeshRendererProperties>();
	}
};

// Class Niagara.NiagaraLightRendererProperties
// 0x0010 (0x0038 - 0x0028)
class UNiagaraLightRendererProperties final : public UNiagaraEffectRendererProperties
{
public:
	float                                         RadiusScale;                                       // 0x0028(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                ColorAdd;                                          // 0x002C(0x000C)(Edit, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraLightRendererProperties">();
	}
	static class UNiagaraLightRendererProperties* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraLightRendererProperties>();
	}
};

// Class Niagara.NiagaraFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UNiagaraFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static class UNiagaraComponent* SpawnEffectAtLocation(class UObject* WorldContextObject, class UNiagaraEffect* EffectTemplate, const struct FVector& Location, const struct FRotator& Rotation, bool bAutoDestroy);
	static class UNiagaraComponent* SpawnEffectAttached(class UNiagaraEffect* EffectTemplate, class USceneComponent* AttachToComponent, class FName AttachPointName, const struct FVector& Location, const struct FRotator& Rotation, EAttachLocation LocationType, bool bAutoDestroy);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraFunctionLibrary">();
	}
	static class UNiagaraFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraFunctionLibrary>();
	}
};

// Class Niagara.NiagaraEventReceiverEmitterAction
// 0x0000 (0x0028 - 0x0028)
class UNiagaraEventReceiverEmitterAction : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraEventReceiverEmitterAction">();
	}
	static class UNiagaraEventReceiverEmitterAction* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraEventReceiverEmitterAction>();
	}
};

// Class Niagara.NiagaraEventReceiverEmitterAction_SpawnParticles
// 0x0008 (0x0030 - 0x0028)
class UNiagaraEventReceiverEmitterAction_SpawnParticles final : public UNiagaraEventReceiverEmitterAction
{
public:
	uint32                                        NumParticles;                                      // 0x0028(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraEventReceiverEmitterAction_SpawnParticles">();
	}
	static class UNiagaraEventReceiverEmitterAction_SpawnParticles* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraEventReceiverEmitterAction_SpawnParticles>();
	}
};

// Class Niagara.NiagaraEmitterProperties
// 0x00E0 (0x0108 - 0x0028)
class UNiagaraEmitterProperties final : public UObject
{
public:
	float                                         SpawnRate;                                         // 0x0028(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bLocalSpace;                                       // 0x002C(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterial*                              Material;                                          // 0x0030(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         StartTime;                                         // 0x0038(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         EndTime;                                           // 0x003C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         NumLoops;                                          // 0x0040(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ENiagaraCollisionMode                         CollisionMode;                                     // 0x0044(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_45[0x3];                                       // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraEffectRendererProperties*       RendererProperties;                                // 0x0048(0x0008)(Edit, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, PersistentInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FNiagaraEmitterScriptProperties        UpdateScriptProps;                                 // 0x0050(0x0028)(ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FNiagaraEmitterScriptProperties        SpawnScriptProps;                                  // 0x0078(0x0028)(ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FNiagaraEventScriptProperties          EventHandlerScriptProps;                           // 0x00A0(0x0050)(Edit, ContainsInstancedReference, NativeAccessSpecifierPublic)
	TArray<struct FNiagaraEmitterBurst>           Bursts;                                            // 0x00F0(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
	uint8                                         bInterpolatedSpawning : 1;                         // 0x0100(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Edit, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic))
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraEmitterProperties">();
	}
	static class UNiagaraEmitterProperties* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraEmitterProperties>();
	}
};

// Class Niagara.NiagaraEffect
// 0x0048 (0x0070 - 0x0028)
class UNiagaraEffect final : public UObject
{
public:
	TArray<struct FNiagaraEmitterHandle>          EmitterHandles;                                    // 0x0028(0x0010)(Edit, ZeroConstructor, EditConst, Protected, NativeAccessSpecifierProtected)
	class UNiagaraScript*                         EffectScript;                                      // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TArray<struct FNiagaraParameterBinding>       ParameterBindings;                                 // 0x0040(0x0010)(ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	TArray<struct FNiagaraParameterBinding>       DataInterfaceBindings;                             // 0x0050(0x0010)(ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	TArray<struct FNiagaraEmitterInternalVariableBinding> InternalEmitterVariableBindings;                   // 0x0060(0x0010)(ZeroConstructor, Protected, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraEffect">();
	}
	static class UNiagaraEffect* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraEffect>();
	}
};

// Class Niagara.NiagaraDataInterface
// 0x0000 (0x0028 - 0x0028)
class UNiagaraDataInterface : public UObject
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraDataInterface">();
	}
	static class UNiagaraDataInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraDataInterface>();
	}
};

// Class Niagara.NiagaraDataInterfaceStaticMesh
// 0x01C8 (0x01F0 - 0x0028)
class UNiagaraDataInterfaceStaticMesh final : public UNiagaraDataInterface
{
public:
	class UStaticMesh*                            DefaultMesh;                                       // 0x0028(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 Source;                                            // 0x0030(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FNDIStaticMeshSectionFilter            SectionFilter;                                     // 0x0038(0x0068)(Edit, NativeAccessSpecifierPublic)
	bool                                          bEnableVertexColorRangeSorting;                    // 0x00A0(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A1[0x14F];                                     // 0x00A1(0x014F)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraDataInterfaceStaticMesh">();
	}
	static class UNiagaraDataInterfaceStaticMesh* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraDataInterfaceStaticMesh>();
	}
};

// Class Niagara.NiagaraDataInterfaceSpline
// 0x0098 (0x00C0 - 0x0028)
class UNiagaraDataInterfaceSpline final : public UNiagaraDataInterface
{
public:
	class AActor*                                 Source;                                            // 0x0028(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_30[0x90];                                      // 0x0030(0x0090)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraDataInterfaceSpline">();
	}
	static class UNiagaraDataInterfaceSpline* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraDataInterfaceSpline>();
	}
};

// Class Niagara.NiagaraDataInterfaceCurlNoise
// 0x0000 (0x0028 - 0x0028)
class UNiagaraDataInterfaceCurlNoise final : public UNiagaraDataInterface
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraDataInterfaceCurlNoise">();
	}
	static class UNiagaraDataInterfaceCurlNoise* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraDataInterfaceCurlNoise>();
	}
};

// Class Niagara.NiagaraDataInterfaceCurveBase
// 0x0000 (0x0028 - 0x0028)
class UNiagaraDataInterfaceCurveBase : public UNiagaraDataInterface
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraDataInterfaceCurveBase">();
	}
	static class UNiagaraDataInterfaceCurveBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraDataInterfaceCurveBase>();
	}
};

// Class Niagara.NiagaraDataInterfaceColorCurve
// 0x01C0 (0x01E8 - 0x0028)
class UNiagaraDataInterfaceColorCurve final : public UNiagaraDataInterfaceCurveBase
{
public:
	struct FRichCurve                             RedCurve;                                          // 0x0028(0x0070)(Edit, NativeAccessSpecifierPublic)
	struct FRichCurve                             GreenCurve;                                        // 0x0098(0x0070)(Edit, NativeAccessSpecifierPublic)
	struct FRichCurve                             BlueCurve;                                         // 0x0108(0x0070)(Edit, NativeAccessSpecifierPublic)
	struct FRichCurve                             AlphaCurve;                                        // 0x0178(0x0070)(Edit, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraDataInterfaceColorCurve">();
	}
	static class UNiagaraDataInterfaceColorCurve* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraDataInterfaceColorCurve>();
	}
};

// Class Niagara.NiagaraDataInterfaceVectorCurve
// 0x0150 (0x0178 - 0x0028)
class UNiagaraDataInterfaceVectorCurve final : public UNiagaraDataInterfaceCurveBase
{
public:
	struct FRichCurve                             XCurve;                                            // 0x0028(0x0070)(Edit, NativeAccessSpecifierPublic)
	struct FRichCurve                             YCurve;                                            // 0x0098(0x0070)(Edit, NativeAccessSpecifierPublic)
	struct FRichCurve                             ZCurve;                                            // 0x0108(0x0070)(Edit, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraDataInterfaceVectorCurve">();
	}
	static class UNiagaraDataInterfaceVectorCurve* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraDataInterfaceVectorCurve>();
	}
};

// Class Niagara.NiagaraDataInterfaceCurve
// 0x0070 (0x0098 - 0x0028)
class UNiagaraDataInterfaceCurve final : public UNiagaraDataInterfaceCurveBase
{
public:
	struct FRichCurve                             Curve;                                             // 0x0028(0x0070)(Edit, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraDataInterfaceCurve">();
	}
	static class UNiagaraDataInterfaceCurve* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraDataInterfaceCurve>();
	}
};

// Class Niagara.NiagaraComponent
// 0x0050 (0x08C0 - 0x0870)
class UNiagaraComponent final : public UPrimitiveComponent
{
public:
	class UNiagaraEffect*                         Asset;                                             // 0x0868(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_870[0x10];                                     // 0x0870(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FNiagaraVariable>               EffectParameterLocalOverrides;                     // 0x0880(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FNiagaraScriptDataInterfaceInfo> EffectDataInterfaceLocalOverrides;                 // 0x0890(0x0010)(Edit, ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	TArray<class UNiagaraDataInterface*>          InstanceDataInterfaces;                            // 0x08A0(0x0010)(ZeroConstructor, Transient, DuplicateTransient, NativeAccessSpecifierPublic)
	bool                                          bRenderingEnabled;                                 // 0x08B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8B1[0xF];                                      // 0x08B1(0x000F)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ReinitializeEffect();
	void ResetEffect();
	void SetNiagaraEmitterSpawnRate(const class FString& InEmitterName, float InValue);
	void SetNiagaraStaticMeshDataInterfaceActor(const class FString& InVariableName, class AActor* InSource);
	void SetNiagaraVariableBool(const class FString& InVariableName, bool InValue);
	void SetNiagaraVariableFloat(const class FString& InVariableName, float InValue);
	void SetNiagaraVariableVec2(const class FString& InVariableName, const struct FVector2D& InValue);
	void SetNiagaraVariableVec3(const class FString& InVariableName, const struct FVector& InValue);
	void SetNiagaraVariableVec4(const class FString& InVariableName, const struct FVector4& InValue);
	void SetRenderingEnabled(bool bInRenderingEnabled);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraComponent">();
	}
	static class UNiagaraComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNiagaraComponent>();
	}
};

// Class Niagara.NiagaraActor
// 0x0010 (0x05E0 - 0x05D0)
class ANiagaraActor final : public AActor
{
public:
	class UNiagaraComponent*                      NiagaraComponent;                                  // 0x05D0(0x0008)(Edit, ExportObject, ZeroConstructor, EditConst, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_5D8[0x8];                                      // 0x05D8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"NiagaraActor">();
	}
	static class ANiagaraActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANiagaraActor>();
	}
};

}

