#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_WoodWallWithDoor

#include "Basic.hpp"

#include "PrimalItemStructure_BaseWallWithDoor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_WoodWallWithDoor.PrimalItemStructure_WoodWallWithDoor_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemStructure_WoodWallWithDoor_C final : public UPrimalItemStructure_BaseWallWithDoor_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemStructure_WoodWallWithDoor_C">();
	}
	static class UPrimalItemStructure_WoodWallWithDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_WoodWallWithDoor_C>();
	}
};

}

