

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_DinoImplant_Base

#include "Basic.hpp"

#include "PrimalItem_DinoImplant_Base_classes.hpp"
#include "PrimalItem_DinoImplant_Base_parameters.hpp"


namespace SDK
{

// Function PrimalItem_DinoImplant_Base.PrimalItem_DinoImplant_Base_C.BPCanAddToInventory
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimalInventoryComponent*        ToInventory                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UPrimalItem_DinoImplant_Base_C::BPCanAddToInventory(class UPrimalInventoryComponent* ToInventory)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalItem_DinoImplant_Base_C", "BPCanAddToInventory");

	Params::PrimalItem_DinoImplant_Base_C_BPCanAddToInventory Parms{};

	Parms.ToInventory = ToInventory;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

