#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructureGeneric

#include "Basic.hpp"

#include "PrimalItemConsumableGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructureGeneric.PrimalItemStructureGeneric_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemStructureGeneric_C : public UPrimalItemConsumableGeneric_C
{
public:
	void GetOverrideUseString(class FText* UseString);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemStructureGeneric_C">();
	}
	static class UPrimalItemStructureGeneric_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructureGeneric_C>();
	}
};

}

