#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_ScubaShirt_SuitWithTank

#include "Basic.hpp"

#include "PrimalItemArmor_BaseShirt_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemArmor_ScubaShirt_SuitWithTank.PrimalItemArmor_ScubaShirt_SuitWithTank_C
// 0x0030 (0x0A88 - 0x0A58)
class UPrimalItemArmor_ScubaShirt_SuitWithTank_C final : public UPrimalItemArmor_BaseShirt_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0A58(0x0008)(Transient, DuplicateTransient)
	TSoftClassPtr<class UClass>                   EquippedBuff;                                      // 0x0A60(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class UPrimalItem*                            SelfObj;                                           // 0x0A80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BlueprintEquipped(bool bIsFromSaveGame);
	void BlueprintUnequipped();
	void ExecuteUbergraph_PrimalItemArmor_ScubaShirt_SuitWithTank(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemArmor_ScubaShirt_SuitWithTank_C">();
	}
	static class UPrimalItemArmor_ScubaShirt_SuitWithTank_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemArmor_ScubaShirt_SuitWithTank_C>();
	}
};

}

