#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemDye_Sky

#include "Basic.hpp"

#include "PrimalItemDyeGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemDye_Sky.PrimalItemDye_Sky_C
// 0x0000 (0x0A80 - 0x0A80)
class UPrimalItemDye_Sky_C final : public UPrimalItemDyeGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemDye_Sky_C">();
	}
	static class UPrimalItemDye_Sky_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemDye_Sky_C>();
	}
};

}

