#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_Bookshelf

#include "Basic.hpp"

#include "PrimalItemStructureGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_Bookshelf.PrimalItemStructure_Bookshelf_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemStructure_Bookshelf_C final : public UPrimalItemStructureGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemStructure_Bookshelf_C">();
	}
	static class UPrimalItemStructure_Bookshelf_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_Bookshelf_C>();
	}
};

}

