#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_WoodGate

#include "Basic.hpp"

#include "PrimalItemStructure_BaseGate_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_WoodGate.PrimalItemStructure_WoodGate_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemStructure_WoodGate_C final : public UPrimalItemStructure_BaseGate_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemStructure_WoodGate_C">();
	}
	static class UPrimalItemStructure_WoodGate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_WoodGate_C>();
	}
};

}

