#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_StonePipeIntake

#include "Basic.hpp"

#include "PrimalItemStructure_BaseStonePipe_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_StonePipeIntake.PrimalItemStructure_StonePipeIntake_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemStructure_StonePipeIntake_C final : public UPrimalItemStructure_BaseStonePipe_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemStructure_StonePipeIntake_C">();
	}
	static class UPrimalItemStructure_StonePipeIntake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_StonePipeIntake_C>();
	}
};

}

