#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemDye_Slate

#include "Basic.hpp"

#include "PrimalItemDyeGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemDye_Slate.PrimalItemDye_Slate_C
// 0x0000 (0x0A80 - 0x0A80)
class UPrimalItemDye_Slate_C final : public UPrimalItemDyeGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemDye_Slate_C">();
	}
	static class UPrimalItemDye_Slate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemDye_Slate_C>();
	}
};

}

