#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_WoodSign_Wall

#include "Basic.hpp"

#include "PrimalItemStructure_BaseSign_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_WoodSign_Wall.PrimalItemStructure_WoodSign_Wall_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemStructure_WoodSign_Wall_C final : public UPrimalItemStructure_BaseSign_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemStructure_WoodSign_Wall_C">();
	}
	static class UPrimalItemStructure_WoodSign_Wall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_WoodSign_Wall_C>();
	}
};

}

