#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_BaseWall

#include "Basic.hpp"

#include "PrimalItemStructureGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_BaseWall.PrimalItemStructure_BaseWall_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemStructure_BaseWall_C : public UPrimalItemStructureGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemStructure_BaseWall_C">();
	}
	static class UPrimalItemStructure_BaseWall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_BaseWall_C>();
	}
};

}

