#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemConsumable_Seed_Stimberry

#include "Basic.hpp"

#include "PrimalItemConsumable_Seed_BaseBerry_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemConsumable_Seed_Stimberry.PrimalItemConsumable_Seed_Stimberry_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemConsumable_Seed_Stimberry_C final : public UPrimalItemConsumable_Seed_BaseBerry_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemConsumable_Seed_Stimberry_C">();
	}
	static class UPrimalItemConsumable_Seed_Stimberry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemConsumable_Seed_Stimberry_C>();
	}
};

}

