#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemDye_Tangerine

#include "Basic.hpp"

#include "PrimalItemDyeGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemDye_Tangerine.PrimalItemDye_Tangerine_C
// 0x0000 (0x0A80 - 0x0A80)
class UPrimalItemDye_Tangerine_C final : public UPrimalItemDyeGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemDye_Tangerine_C">();
	}
	static class UPrimalItemDye_Tangerine_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemDye_Tangerine_C>();
	}
};

}

