#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_WoodStairs

#include "Basic.hpp"

#include "PrimalItemStructure_BaseWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_WoodStairs.PrimalItemStructure_WoodStairs_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemStructure_WoodStairs_C final : public UPrimalItemStructure_BaseWall_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemStructure_WoodStairs_C">();
	}
	static class UPrimalItemStructure_WoodStairs_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_WoodStairs_C>();
	}
};

}

