#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_ThatchWallWithDoor

#include "Basic.hpp"

#include "PrimalItemStructure_BaseWallWithDoor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_ThatchWallWithDoor.PrimalItemStructure_ThatchWallWithDoor_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemStructure_ThatchWallWithDoor_C final : public UPrimalItemStructure_BaseWallWithDoor_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemStructure_ThatchWallWithDoor_C">();
	}
	static class UPrimalItemStructure_ThatchWallWithDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_ThatchWallWithDoor_C>();
	}
};

}

