#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_WoodWindow

#include "Basic.hpp"

#include "PrimalItemStructure_BaseWindow_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_WoodWindow.PrimalItemStructure_WoodWindow_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemStructure_WoodWindow_C final : public UPrimalItemStructure_BaseWindow_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemStructure_WoodWindow_C">();
	}
	static class UPrimalItemStructure_WoodWindow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_WoodWindow_C>();
	}
};

}

