#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemConsumable_Seed_Rockarrot

#include "Basic.hpp"

#include "PrimalItemConsumable_Seed_BaseVeggie_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemConsumable_Seed_Rockarrot.PrimalItemConsumable_Seed_Rockarrot_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemConsumable_Seed_Rockarrot_C final : public UPrimalItemConsumable_Seed_BaseVeggie_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemConsumable_Seed_Rockarrot_C">();
	}
	static class UPrimalItemConsumable_Seed_Rockarrot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemConsumable_Seed_Rockarrot_C>();
	}
};

}

