#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_TekHelmet

#include "Basic.hpp"


namespace SDK::Params
{

// Function PrimalItemArmor_TekHelmet.PrimalItemArmor_TekHelmet_C.RequiresActivationForDamageVolumeNegation
// 0x0003 (0x0003 - 0x0000)
struct PrimalItemArmor_TekHelmet_C_RequiresActivationForDamageVolumeNegation final
{
public:
	bool                                          IsActivated;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          ReturnValue;                                       // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsCharged_Charged;                        // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};

}

