#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_ImprintBoost_Base

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItem_ImprintBoost_Base.PrimalItem_ImprintBoost_Base_C
// 0x0000 (0x0AB0 - 0x0AB0)
class UPrimalItem_ImprintBoost_Base_C final : public UPrimalItem_ImprintBoost
{
public:
	bool BPLocalCanUse();
	void GetOverrideUseString(class FText* UseString);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItem_ImprintBoost_Base_C">();
	}
	static class UPrimalItem_ImprintBoost_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItem_ImprintBoost_Base_C>();
	}
};

}

