#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_ThatchWall_Sloped_Right

#include "Basic.hpp"

#include "PrimalItemStructure_BaseWall_Sloped_Right_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_ThatchWall_Sloped_Right.PrimalItemStructure_ThatchWall_Sloped_Right_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemStructure_ThatchWall_Sloped_Right_C final : public UPrimalItemStructure_BaseWall_Sloped_Right_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemStructure_ThatchWall_Sloped_Right_C">();
	}
	static class UPrimalItemStructure_ThatchWall_Sloped_Right_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_ThatchWall_Sloped_Right_C>();
	}
};

}

