#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemDye_ActuallyMagenta

#include "Basic.hpp"

#include "PrimalItemDyeGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemDye_ActuallyMagenta.PrimalItemDye_ActuallyMagenta_C
// 0x0000 (0x0A80 - 0x0A80)
class UPrimalItemDye_ActuallyMagenta_C final : public UPrimalItemDyeGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemDye_ActuallyMagenta_C">();
	}
	static class UPrimalItemDye_ActuallyMagenta_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemDye_ActuallyMagenta_C>();
	}
};

}

