#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_SleepingBag_Base

#include "Basic.hpp"

#include "PrimalItemStructureGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_SleepingBag_Base.PrimalItemStructure_SleepingBag_Base_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemStructure_SleepingBag_Base_C : public UPrimalItemStructureGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemStructure_SleepingBag_Base_C">();
	}
	static class UPrimalItemStructure_SleepingBag_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_SleepingBag_Base_C>();
	}
};

}

