

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemConsumable_Egg

#include "Basic.hpp"

#include "PrimalItemConsumable_Egg_classes.hpp"
#include "PrimalItemConsumable_Egg_parameters.hpp"


namespace SDK
{

// Function PrimalItemConsumable_Egg.PrimalItemConsumable_Egg_C.BPForceGetConfirmationString
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UPrimalItemConsumable_Egg_C::BPForceGetConfirmationString()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalItemConsumable_Egg_C", "BPForceGetConfirmationString");

	Params::PrimalItemConsumable_Egg_C_BPForceGetConfirmationString Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

