

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemConsumable_CureLow

#include "Basic.hpp"

#include "PrimalItemConsumable_CureLow_classes.hpp"
#include "PrimalItemConsumable_CureLow_parameters.hpp"


namespace SDK
{

// Function PrimalItemConsumable_CureLow.PrimalItemConsumable_CureLow_C.GetOverrideUseString
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             UseString                                              (Parm, OutParm)

void UPrimalItemConsumable_CureLow_C::GetOverrideUseString(class FText* UseString)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalItemConsumable_CureLow_C", "GetOverrideUseString");

	Params::PrimalItemConsumable_CureLow_C_GetOverrideUseString Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (UseString != nullptr)
		*UseString = std::move(Parms.UseString);
}


// Function PrimalItemConsumable_CureLow.PrimalItemConsumable_CureLow_C.BlueprintUsed
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AShooterPlayerController*         ForPC                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UPrimalItemConsumable_CureLow_C::BlueprintUsed(class AShooterPlayerController* ForPC)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalItemConsumable_CureLow_C", "BlueprintUsed");

	Params::PrimalItemConsumable_CureLow_C_BlueprintUsed Parms{};

	Parms.ForPC = ForPC;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

