

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_ImprintBoost_Base

#include "Basic.hpp"

#include "PrimalItem_ImprintBoost_Base_classes.hpp"
#include "PrimalItem_ImprintBoost_Base_parameters.hpp"


namespace SDK
{

// Function PrimalItem_ImprintBoost_Base.PrimalItem_ImprintBoost_Base_C.BPLocalCanUse
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UPrimalItem_ImprintBoost_Base_C::BPLocalCanUse()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalItem_ImprintBoost_Base_C", "BPLocalCanUse");

	Params::PrimalItem_ImprintBoost_Base_C_BPLocalCanUse Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PrimalItem_ImprintBoost_Base.PrimalItem_ImprintBoost_Base_C.GetOverrideUseString
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             UseString                                              (Parm, OutParm)

void UPrimalItem_ImprintBoost_Base_C::GetOverrideUseString(class FText* UseString)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalItem_ImprintBoost_Base_C", "GetOverrideUseString");

	Params::PrimalItem_ImprintBoost_Base_C_GetOverrideUseString Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (UseString != nullptr)
		*UseString = std::move(Parms.UseString);
}

}

