#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemConsumableSoap

#include "Basic.hpp"

#include "PrimalItemConsumableGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemConsumableSoap.PrimalItemConsumableSoap_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemConsumableSoap_C final : public UPrimalItemConsumableGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemConsumableSoap_C">();
	}
	static class UPrimalItemConsumableSoap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemConsumableSoap_C>();
	}
};

}

