

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_Fist

#include "Basic.hpp"

#include "PrimalItem_Fist_classes.hpp"
#include "PrimalItem_Fist_parameters.hpp"


namespace SDK
{

// Function PrimalItem_Fist.PrimalItem_Fist_C.GetOverrideUseString
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             UseString                                              (Parm, OutParm)

void UPrimalItem_Fist_C::GetOverrideUseString(class FText* UseString)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalItem_Fist_C", "GetOverrideUseString");

	Params::PrimalItem_Fist_C_GetOverrideUseString Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (UseString != nullptr)
		*UseString = std::move(Parms.UseString);
}

}

