#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_StonePipeIntersection

#include "Basic.hpp"

#include "PrimalItemStructure_BaseStonePipe_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemStructure_StonePipeIntersection.PrimalItemStructure_StonePipeIntersection_C
// 0x0000 (0x0A58 - 0x0A58)
class UPrimalItemStructure_StonePipeIntersection_C final : public UPrimalItemStructure_BaseStonePipe_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrimalItemStructure_StonePipeIntersection_C">();
	}
	static class UPrimalItemStructure_StonePipeIntersection_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_StonePipeIntersection_C>();
	}
};

}

