

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PromoTextEntryDialog

#include "Basic.hpp"

#include "PromoTextEntryDialog_classes.hpp"
#include "PromoTextEntryDialog_parameters.hpp"


namespace SDK
{

// Function PromoTextEntryDialog.PromoTextEntryDialog_C.ExecuteUbergraph_PromoTextEntryDialog
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPromoTextEntryDialog_C::ExecuteUbergraph_PromoTextEntryDialog(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PromoTextEntryDialog_C", "ExecuteUbergraph_PromoTextEntryDialog");

	Params::PromoTextEntryDialog_C_ExecuteUbergraph_PromoTextEntryDialog Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PromoTextEntryDialog.PromoTextEntryDialog_C.BndEvt__TextEntry_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UPromoTextEntryDialog_C::BndEvt__TextEntry_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PromoTextEntryDialog_C", "BndEvt__TextEntry_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature");

	Params::PromoTextEntryDialog_C_BndEvt__TextEntry_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PromoTextEntryDialog.PromoTextEntryDialog_C.BndEvt__SPButton_K2Node_ComponentBoundEvent_70_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UPromoTextEntryDialog_C::BndEvt__SPButton_K2Node_ComponentBoundEvent_70_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PromoTextEntryDialog_C", "BndEvt__SPButton_K2Node_ComponentBoundEvent_70_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PromoTextEntryDialog.PromoTextEntryDialog_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UPromoTextEntryDialog_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PromoTextEntryDialog_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PromoTextEntryDialog.PromoTextEntryDialog_C.UpdateButtons
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UPromoTextEntryDialog_C::UpdateButtons()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PromoTextEntryDialog_C", "UpdateButtons");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PromoTextEntryDialog.PromoTextEntryDialog_C.Initialize Promo Dialog
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Single_Player                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FString                           With_Promo                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class FText                             Override_Title                                         (BlueprintVisible, BlueprintReadOnly, Parm)

void UPromoTextEntryDialog_C::Initialize_Promo_Dialog(bool Single_Player, const class FString& With_Promo, const class FText& Override_Title)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PromoTextEntryDialog_C", "Initialize Promo Dialog");

	Params::PromoTextEntryDialog_C_Initialize_Promo_Dialog Parms{};

	Parms.Single_Player = Single_Player;
	Parms.With_Promo = std::move(With_Promo);
	Parms.Override_Title = std::move(Override_Title);

	UObject::ProcessEvent(Func, &Parms);
}

}

