#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Raft_Anim_BP

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Raft_Anim_BP.Raft_Anim_BP_C
// 0x03A8 (0x0720 - 0x0378)
class URaft_Anim_BP_C final : public UAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0378(0x0008)(Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_94D59C31486544DF9AF6AC88FAEF1069; // 0x0380(0x0048)()
	uint8                                         Pad_3C8[0x8];                                      // 0x03C8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_4F6273104DCEF72B417862B7BDDEA4F6; // 0x03D0(0x00F0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_F8DCBE1742B405E0C08DDFB5F6C96F5B; // 0x04C0(0x0048)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_1435E03149126C9CE47533B36F33FB20; // 0x0508(0x00C8)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_C35AA1924F2CB0CC0F975A8A0DE8E1F3; // 0x05D0(0x0048)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_DC07419F4C539659D855FB8EF4541AB4; // 0x0618(0x0070)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_05E6197E4FAA219011C3ECA4D8C9133D; // 0x0688(0x0070)()
	struct FVector                                RootLocationOffset;                                // 0x06F8(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               RootRotationOffset;                                // 0x0704(0x000C)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bIsMoving;                                         // 0x0710(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Raft_Anim_BP_AnimGraphNode_BlendListByBool_1435E03149126C9CE47533B36F33FB20();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Raft_Anim_BP_AnimGraphNode_ModifyBone_4F6273104DCEF72B417862B7BDDEA4F6();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void ExecuteUbergraph_Raft_Anim_BP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Raft_Anim_BP_C">();
	}
	static class URaft_Anim_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URaft_Anim_BP_C>();
	}
};

}

