

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RaftOptionsMenu

#include "Basic.hpp"

#include "RaftOptionsMenu_classes.hpp"
#include "RaftOptionsMenu_parameters.hpp"


namespace SDK
{

// Function RaftOptionsMenu.RaftOptionsMenu_C.ExecuteUbergraph_RaftOptionsMenu
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URaftOptionsMenu_C::ExecuteUbergraph_RaftOptionsMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "ExecuteUbergraph_RaftOptionsMenu");

	Params::RaftOptionsMenu_C_ExecuteUbergraph_RaftOptionsMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.BndEvt__ClaimButton_K2Node_ComponentBoundEvent_236_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void URaftOptionsMenu_C::BndEvt__ClaimButton_K2Node_ComponentBoundEvent_236_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "BndEvt__ClaimButton_K2Node_ComponentBoundEvent_236_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.BndEvt__UnclaimButton_K2Node_ComponentBoundEvent_167_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void URaftOptionsMenu_C::BndEvt__UnclaimButton_K2Node_ComponentBoundEvent_167_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "BndEvt__UnclaimButton_K2Node_ComponentBoundEvent_167_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.BndEvt__DemolishButton_K2Node_ComponentBoundEvent_137_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void URaftOptionsMenu_C::BndEvt__DemolishButton_K2Node_ComponentBoundEvent_137_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "BndEvt__DemolishButton_K2Node_ComponentBoundEvent_137_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.BndEvt__NameBox_K2Node_ComponentBoundEvent_87_OnEditableTextBoxCommittedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URaftOptionsMenu_C::BndEvt__NameBox_K2Node_ComponentBoundEvent_87_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "BndEvt__NameBox_K2Node_ComponentBoundEvent_87_OnEditableTextBoxCommittedEvent__DelegateSignature");

	Params::RaftOptionsMenu_C_BndEvt__NameBox_K2Node_ComponentBoundEvent_87_OnEditableTextBoxCommittedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URaftOptionsMenu_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "Tick");

	Params::RaftOptionsMenu_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.BndEvt__NameBox_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void URaftOptionsMenu_C::BndEvt__NameBox_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "BndEvt__NameBox_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature");

	Params::RaftOptionsMenu_C_BndEvt__NameBox_K2Node_ComponentBoundEvent_0_OnEditableTextBoxChangedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.BndEvt__ApplyNameButton_K2Node_ComponentBoundEvent_28_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void URaftOptionsMenu_C::BndEvt__ApplyNameButton_K2Node_ComponentBoundEvent_28_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "BndEvt__ApplyNameButton_K2Node_ComponentBoundEvent_28_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.BndEvt__EditNameButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void URaftOptionsMenu_C::BndEvt__EditNameButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "BndEvt__EditNameButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.BndEvt__ApplyButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void URaftOptionsMenu_C::BndEvt__ApplyButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "BndEvt__ApplyButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.BndEvt__ButtonToTrapClicks_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void URaftOptionsMenu_C::BndEvt__ButtonToTrapClicks_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "BndEvt__ButtonToTrapClicks_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.On_OrdersCombo_GenerateWidget_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* URaftOptionsMenu_C::On_OrdersCombo_GenerateWidget_0(const class FString& Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "On_OrdersCombo_GenerateWidget_0");

	Params::RaftOptionsMenu_C_On_OrdersCombo_GenerateWidget_0 Parms{};

	Parms.Item = std::move(Item);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.On_OrdersCombo_GenerateWidget_1
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* URaftOptionsMenu_C::On_OrdersCombo_GenerateWidget_1(const class FString& Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "On_OrdersCombo_GenerateWidget_1");

	Params::RaftOptionsMenu_C_On_OrdersCombo_GenerateWidget_1 Parms{};

	Parms.Item = std::move(Item);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.On_OrdersCombo_GenerateWidget_2
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* URaftOptionsMenu_C::On_OrdersCombo_GenerateWidget_2(const class FString& Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "On_OrdersCombo_GenerateWidget_2");

	Params::RaftOptionsMenu_C_On_OrdersCombo_GenerateWidget_2 Parms{};

	Parms.Item = std::move(Item);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.OnGenerateWidget_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Item                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* URaftOptionsMenu_C::OnGenerateWidget_0(const class FString& Item)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "OnGenerateWidget_0");

	Params::RaftOptionsMenu_C_OnGenerateWidget_0 Parms{};

	Parms.Item = std::move(Item);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.MakeVisible
// (Public, BlueprintCallable, BlueprintEvent)

void URaftOptionsMenu_C::MakeVisible()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "MakeVisible");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.EnabledByCode
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void URaftOptionsMenu_C::EnabledByCode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "EnabledByCode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.ApplyName
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void URaftOptionsMenu_C::ApplyName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "ApplyName");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.DisabledByCode
// (Public, BlueprintCallable, BlueprintEvent)

void URaftOptionsMenu_C::DisabledByCode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "DisabledByCode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.ApplyChanges
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ClearDialogActor                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void URaftOptionsMenu_C::ApplyChanges(bool ClearDialogActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "ApplyChanges");

	Params::RaftOptionsMenu_C_ApplyChanges Parms{};

	Parms.ClearDialogActor = ClearDialogActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.InitializeMenu
// (Public, BlueprintCallable, BlueprintEvent)

void URaftOptionsMenu_C::InitializeMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "InitializeMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RaftOptionsMenu.RaftOptionsMenu_C.WaitForServerClaim
// (Public, BlueprintCallable, BlueprintEvent)

void URaftOptionsMenu_C::WaitForServerClaim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RaftOptionsMenu_C", "WaitForServerClaim");

	UObject::ProcessEvent(Func, nullptr);
}

}

