#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Raft_BP

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Raft_BP.Raft_BP_C
// 0x0060 (0x2350 - 0x22F0)
class ARaft_BP_C final : public APrimalRaft
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x22F0(0x0008)(Transient, DuplicateTransient)
	class USkeletalMeshComponent*                 Raft_DodoPlume_DodoPlume;                          // 0x22F8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 MastSkeletal;                                      // 0x2300(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               WaterRaftEffect;                                   // 0x2308(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 StructureSurface;                                  // 0x2310(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDinoCharacterStatusComponent_BP_C*     DinoCharacterStatus_BP_C1;                         // 0x2318(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TSoftClassPtr<class UClass>                   DodoFeatherResource;                               // 0x2320(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          bHasDodoPlume;                                     // 0x2340(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, SaveGame, IsPlainOldData, RepNotify, NoDestructor)

public:
	void OnRep_bHasDodoPlume();
	bool BPCanConsumeResource(class UPrimalItem* Item);
	void UserConstructionScript();
	void BPOnFedDino(class UPrimalItem* FoodItem, class UPrimalInventoryComponent* FromInventory);
	void BPOnBonesHidden(bool BonesHidden);
	void ReceiveBeginPlay();
	void ExecuteUbergraph_Raft_BP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Raft_BP_C">();
	}
	static class ARaft_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARaft_BP_C>();
	}
};

}

