

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Raft_Anim_BP

#include "Basic.hpp"

#include "Raft_Anim_BP_classes.hpp"
#include "Raft_Anim_BP_parameters.hpp"


namespace SDK
{

// Function Raft_Anim_BP.Raft_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Raft_Anim_BP_AnimGraphNode_BlendListByBool_1435E03149126C9CE47533B36F33FB20
// (BlueprintEvent)

void URaft_Anim_BP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Raft_Anim_BP_AnimGraphNode_BlendListByBool_1435E03149126C9CE47533B36F33FB20()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Raft_Anim_BP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Raft_Anim_BP_AnimGraphNode_BlendListByBool_1435E03149126C9CE47533B36F33FB20");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Raft_Anim_BP.Raft_Anim_BP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Raft_Anim_BP_AnimGraphNode_ModifyBone_4F6273104DCEF72B417862B7BDDEA4F6
// (BlueprintEvent)

void URaft_Anim_BP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Raft_Anim_BP_AnimGraphNode_ModifyBone_4F6273104DCEF72B417862B7BDDEA4F6()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Raft_Anim_BP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Raft_Anim_BP_AnimGraphNode_ModifyBone_4F6273104DCEF72B417862B7BDDEA4F6");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Raft_Anim_BP.Raft_Anim_BP_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URaft_Anim_BP_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Raft_Anim_BP_C", "BlueprintUpdateAnimation");

	Params::Raft_Anim_BP_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Raft_Anim_BP.Raft_Anim_BP_C.ExecuteUbergraph_Raft_Anim_BP
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URaft_Anim_BP_C::ExecuteUbergraph_Raft_Anim_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Raft_Anim_BP_C", "ExecuteUbergraph_Raft_Anim_BP");

	Params::Raft_Anim_BP_C_ExecuteUbergraph_Raft_Anim_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

