#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ScreenshotDialog

#include "Basic.hpp"


namespace SDK::Params
{

// Function ScreenshotDialog.ScreenshotDialog_C.ExecuteUbergraph_ScreenshotDialog
// 0x0004 (0x0004 - 0x0000)
struct ScreenshotDialog_C_ExecuteUbergraph_ScreenshotDialog final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

