

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ServerStatsView

#include "Basic.hpp"

#include "ServerStatsView_classes.hpp"
#include "ServerStatsView_parameters.hpp"


namespace SDK
{

// Function ServerStatsView.ServerStatsView_C.ExecuteUbergraph_ServerStatsView
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UServerStatsView_C::ExecuteUbergraph_ServerStatsView(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ServerStatsView_C", "ExecuteUbergraph_ServerStatsView");

	Params::ServerStatsView_C_ExecuteUbergraph_ServerStatsView Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ServerStatsView.ServerStatsView_C.BndEvt__Info_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UServerStatsView_C::BndEvt__Info_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ServerStatsView_C", "BndEvt__Info_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ServerStatsView.ServerStatsView_C.BndEvt__ZoomButton_K2Node_ComponentBoundEvent_175_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UServerStatsView_C::BndEvt__ZoomButton_K2Node_ComponentBoundEvent_175_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ServerStatsView_C", "BndEvt__ZoomButton_K2Node_ComponentBoundEvent_175_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ServerStatsView.ServerStatsView_C.BndEvt__SelectStructureKills_K2Node_ComponentBoundEvent_154_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UServerStatsView_C::BndEvt__SelectStructureKills_K2Node_ComponentBoundEvent_154_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ServerStatsView_C", "BndEvt__SelectStructureKills_K2Node_ComponentBoundEvent_154_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ServerStatsView.ServerStatsView_C.BndEvt__SelectCreatureKills_K2Node_ComponentBoundEvent_134_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UServerStatsView_C::BndEvt__SelectCreatureKills_K2Node_ComponentBoundEvent_134_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ServerStatsView_C", "BndEvt__SelectCreatureKills_K2Node_ComponentBoundEvent_134_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ServerStatsView.ServerStatsView_C.BndEvt__SelectPlayerKills_K2Node_ComponentBoundEvent_110_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UServerStatsView_C::BndEvt__SelectPlayerKills_K2Node_ComponentBoundEvent_110_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ServerStatsView_C", "BndEvt__SelectPlayerKills_K2Node_ComponentBoundEvent_110_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ServerStatsView.ServerStatsView_C.BndEvt__SelectLogins_K2Node_ComponentBoundEvent_92_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UServerStatsView_C::BndEvt__SelectLogins_K2Node_ComponentBoundEvent_92_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ServerStatsView_C", "BndEvt__SelectLogins_K2Node_ComponentBoundEvent_92_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ServerStatsView.ServerStatsView_C.BndEvt__SelectPopulation_K2Node_ComponentBoundEvent_75_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UServerStatsView_C::BndEvt__SelectPopulation_K2Node_ComponentBoundEvent_75_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ServerStatsView_C", "BndEvt__SelectPopulation_K2Node_ComponentBoundEvent_75_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ServerStatsView.ServerStatsView_C.StatsDownloaded
// (Event, Protected, BlueprintEvent)

void UServerStatsView_C::StatsDownloaded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ServerStatsView_C", "StatsDownloaded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ServerStatsView.ServerStatsView_C.SelectedServer
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FServerListEntry                 Entry                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    bSkipDownload                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UServerStatsView_C::SelectedServer(const struct FServerListEntry& Entry, bool bSkipDownload)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ServerStatsView_C", "SelectedServer");

	Params::ServerStatsView_C_SelectedServer Parms{};

	Parms.Entry = std::move(Entry);
	Parms.bSkipDownload = bSkipDownload;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ServerStatsView.ServerStatsView_C.UpdateStatGraph
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UServerStatsView_C::UpdateStatGraph()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ServerStatsView_C", "UpdateStatGraph");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ServerStatsView.ServerStatsView_C.SetBoxText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTextBlock*                       Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   HasTextFontSize                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UServerStatsView_C::SetBoxText(class UTextBlock* Text, const class FText& Value, int32 HasTextFontSize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ServerStatsView_C", "SetBoxText");

	Params::ServerStatsView_C_SetBoxText Parms{};

	Parms.Text = Text;
	Parms.Value = std::move(Value);
	Parms.HasTextFontSize = HasTextFontSize;

	UObject::ProcessEvent(Func, &Parms);
}

}

