#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SimpleBed

#include "Basic.hpp"

#include "BedBaseBP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SimpleBed.SimpleBed_C
// 0x0000 (0x0C88 - 0x0C88)
class ASimpleBed_C final : public ABedBaseBP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SimpleBed_C">();
	}
	static class ASimpleBed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASimpleBed_C>();
	}
};

}

