#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpawnMenuCheatItem

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct SpawnMenuCheatItem.SpawnMenuCheatItem
// 0x0030 (0x0030 - 0x0000)
struct FSpawnMenuCheatItem final
{
public:
	TSoftClassPtr<class UClass>                   Item_4_40BA064949D04009F4EDE6B691429244;           // 0x0000(0x0020)(Edit, BlueprintVisible, HasGetValueTypeHash)
	int32                                         Quantity_14_AC5D409749352B0F0E1224AEE12EC94D;      // 0x0020(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Quality_15_19AE35614DC2A485267BC9BE2C6EA68C;       // 0x0024(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Blueprint_12_4B841B8C428B4549286D11A30CE9D613;     // 0x0028(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          ARKetype_11_39240D374D4FF2785D3D46BE39AD1AF2;      // 0x0029(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
};

}

