#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StructureSettings_BrokenByExplosives_WeakMetalDmg

#include "Basic.hpp"

#include "StructureSettings_BrokenByExplosives_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass StructureSettings_BrokenByExplosives_WeakMetalDmg.StructureSettings_BrokenByExplosives_WeakMetalDmg_C
// 0x0000 (0x0050 - 0x0050)
class UStructureSettings_BrokenByExplosives_WeakMetalDmg_C final : public UStructureSettings_BrokenByExplosives_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"StructureSettings_BrokenByExplosives_WeakMetalDmg_C">();
	}
	static class UStructureSettings_BrokenByExplosives_WeakMetalDmg_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStructureSettings_BrokenByExplosives_WeakMetalDmg_C>();
	}
};

}

