

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SupplyCrate_Cave_QualityTier2

#include "Basic.hpp"

#include "SupplyCrate_Cave_QualityTier2_classes.hpp"


namespace SDK
{

// Function SupplyCrate_Cave_QualityTier2.SupplyCrate_Cave_QualityTier2_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ASupplyCrate_Cave_QualityTier2_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SupplyCrate_Cave_QualityTier2_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

