

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SupplyCrate_Cave_QualityTier3

#include "Basic.hpp"

#include "SupplyCrate_Cave_QualityTier3_classes.hpp"


namespace SDK
{

// Function SupplyCrate_Cave_QualityTier3.SupplyCrate_Cave_QualityTier3_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ASupplyCrate_Cave_QualityTier3_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SupplyCrate_Cave_QualityTier3_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

