#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Vase_Leddica_AnimBlueprint

#include "Basic.hpp"

#include "Chest_AnimBP_Base_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Vase_Leddica_AnimBlueprint.Vase_Leddica_AnimBlueprint_C
// 0x0000 (0x05D8 - 0x05D8)
class UVase_Leddica_AnimBlueprint_C final : public UChest_AnimBP_Base_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Vase_Leddica_AnimBlueprint_C">();
	}
	static class UVase_Leddica_AnimBlueprint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVase_Leddica_AnimBlueprint_C>();
	}
};

}

