

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WDChatBP

#include "Basic.hpp"

#include "WDChatBP_classes.hpp"
#include "WDChatBP_parameters.hpp"


namespace SDK
{

// Function WDChatBP.WDChatBP_C.ExecuteUbergraph_WDChatBP
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWDChatBP_C::ExecuteUbergraph_WDChatBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "ExecuteUbergraph_WDChatBP");

	Params::WDChatBP_C_ExecuteUbergraph_WDChatBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDChatBP.WDChatBP_C.BndEvt__AllianceChannelButton_K2Node_ComponentBoundEvent_217_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__AllianceChannelButton_K2Node_ComponentBoundEvent_217_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__AllianceChannelButton_K2Node_ComponentBoundEvent_217_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.HideChat
// (Event, Public, BlueprintEvent)

void UWDChatBP_C::HideChat()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "HideChat");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.ShowChat
// (Event, Public, BlueprintEvent)

void UWDChatBP_C::ShowChat()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "ShowChat");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__KeyboardButton_K2Node_ComponentBoundEvent_4870_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__KeyboardButton_K2Node_ComponentBoundEvent_4870_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__KeyboardButton_K2Node_ComponentBoundEvent_4870_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__TalkButton_K2Node_ComponentBoundEvent_4853_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__TalkButton_K2Node_ComponentBoundEvent_4853_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__TalkButton_K2Node_ComponentBoundEvent_4853_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__ActivateButton_K2Node_ComponentBoundEvent_344_OnButtonReleasedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__ActivateButton_K2Node_ComponentBoundEvent_344_OnButtonReleasedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__ActivateButton_K2Node_ComponentBoundEvent_344_OnButtonReleasedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__ActivateButton_K2Node_ComponentBoundEvent_354_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__ActivateButton_K2Node_ComponentBoundEvent_354_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__ActivateButton_K2Node_ComponentBoundEvent_354_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__LocalChannelButton_K2Node_ComponentBoundEvent_106_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__LocalChannelButton_K2Node_ComponentBoundEvent_106_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__LocalChannelButton_K2Node_ComponentBoundEvent_106_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__TongueButton_K2Node_ComponentBoundEvent_3899_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__TongueButton_K2Node_ComponentBoundEvent_3899_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__TongueButton_K2Node_ComponentBoundEvent_3899_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__HappyButton_K2Node_ComponentBoundEvent_3850_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__HappyButton_K2Node_ComponentBoundEvent_3850_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__HappyButton_K2Node_ComponentBoundEvent_3850_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__WinkButton_K2Node_ComponentBoundEvent_3802_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__WinkButton_K2Node_ComponentBoundEvent_3802_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__WinkButton_K2Node_ComponentBoundEvent_3802_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__DevilButton_K2Node_ComponentBoundEvent_3755_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__DevilButton_K2Node_ComponentBoundEvent_3755_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__DevilButton_K2Node_ComponentBoundEvent_3755_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__OhButton_K2Node_ComponentBoundEvent_3709_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__OhButton_K2Node_ComponentBoundEvent_3709_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__OhButton_K2Node_ComponentBoundEvent_3709_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__BlankButton_K2Node_ComponentBoundEvent_3664_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__BlankButton_K2Node_ComponentBoundEvent_3664_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__BlankButton_K2Node_ComponentBoundEvent_3664_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__LetsGoButton_K2Node_ComponentBoundEvent_2315_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__LetsGoButton_K2Node_ComponentBoundEvent_2315_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__LetsGoButton_K2Node_ComponentBoundEvent_2315_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__GetOnButton_K2Node_ComponentBoundEvent_2272_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__GetOnButton_K2Node_ComponentBoundEvent_2272_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__GetOnButton_K2Node_ComponentBoundEvent_2272_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__StayHereButton_K2Node_ComponentBoundEvent_2230_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__StayHereButton_K2Node_ComponentBoundEvent_2230_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__StayHereButton_K2Node_ComponentBoundEvent_2230_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__FollowMeButton_K2Node_ComponentBoundEvent_2189_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__FollowMeButton_K2Node_ComponentBoundEvent_2189_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__FollowMeButton_K2Node_ComponentBoundEvent_2189_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__TradeButton_K2Node_ComponentBoundEvent_2067_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__TradeButton_K2Node_ComponentBoundEvent_2067_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__TradeButton_K2Node_ComponentBoundEvent_2067_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__TribeButton_K2Node_ComponentBoundEvent_2028_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__TribeButton_K2Node_ComponentBoundEvent_2028_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__TribeButton_K2Node_ComponentBoundEvent_2028_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__ReadyButton_K2Node_ComponentBoundEvent_1990_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__ReadyButton_K2Node_ComponentBoundEvent_1990_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__ReadyButton_K2Node_ComponentBoundEvent_1990_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__WowButton_K2Node_ComponentBoundEvent_1953_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__WowButton_K2Node_ComponentBoundEvent_1953_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__WowButton_K2Node_ComponentBoundEvent_1953_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__HelpButton_K2Node_ComponentBoundEvent_1917_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__HelpButton_K2Node_ComponentBoundEvent_1917_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__HelpButton_K2Node_ComponentBoundEvent_1917_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__SorryButton_K2Node_ComponentBoundEvent_1882_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__SorryButton_K2Node_ComponentBoundEvent_1882_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__SorryButton_K2Node_ComponentBoundEvent_1882_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__HelloButton_K2Node_ComponentBoundEvent_1848_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__HelloButton_K2Node_ComponentBoundEvent_1848_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__HelloButton_K2Node_ComponentBoundEvent_1848_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__ThanksButton_K2Node_ComponentBoundEvent_1815_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__ThanksButton_K2Node_ComponentBoundEvent_1815_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__ThanksButton_K2Node_ComponentBoundEvent_1815_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__AtButton_K2Node_ComponentBoundEvent_1783_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__AtButton_K2Node_ComponentBoundEvent_1783_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__AtButton_K2Node_ComponentBoundEvent_1783_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__NoButton_K2Node_ComponentBoundEvent_1752_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__NoButton_K2Node_ComponentBoundEvent_1752_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__NoButton_K2Node_ComponentBoundEvent_1752_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__YesButton_K2Node_ComponentBoundEvent_1722_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__YesButton_K2Node_ComponentBoundEvent_1722_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__YesButton_K2Node_ComponentBoundEvent_1722_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__FrownButton_K2Node_ComponentBoundEvent_1693_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__FrownButton_K2Node_ComponentBoundEvent_1693_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__FrownButton_K2Node_ComponentBoundEvent_1693_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__SmileButton_K2Node_ComponentBoundEvent_1676_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__SmileButton_K2Node_ComponentBoundEvent_1676_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__SmileButton_K2Node_ComponentBoundEvent_1676_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__ChatLogButton_K2Node_ComponentBoundEvent_64_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__ChatLogButton_K2Node_ComponentBoundEvent_64_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__ChatLogButton_K2Node_ComponentBoundEvent_64_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.PrimaryAction
// (Event, Public, BlueprintEvent)

void UWDChatBP_C::PrimaryAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "PrimaryAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__Button_57_K2Node_ComponentBoundEvent_193_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__Button_57_K2Node_ComponentBoundEvent_193_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__Button_57_K2Node_ComponentBoundEvent_193_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__GlobalTab_K2Node_ComponentBoundEvent_335_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__GlobalTab_K2Node_ComponentBoundEvent_335_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__GlobalTab_K2Node_ComponentBoundEvent_335_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__LocalTab_K2Node_ComponentBoundEvent_309_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__LocalTab_K2Node_ComponentBoundEvent_309_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__LocalTab_K2Node_ComponentBoundEvent_309_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__TribeTab_K2Node_ComponentBoundEvent_284_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__TribeTab_K2Node_ComponentBoundEvent_284_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__TribeTab_K2Node_ComponentBoundEvent_284_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__AllTab_K2Node_ComponentBoundEvent_211_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__AllTab_K2Node_ComponentBoundEvent_211_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__AllTab_K2Node_ComponentBoundEvent_211_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWDChatBP_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.SecondaryAction
// (Event, Public, BlueprintEvent)

void UWDChatBP_C::SecondaryAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "SecondaryAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.PushEntry
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// struct FChatEntry                       Entry                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWDChatBP_C::PushEntry(const struct FChatEntry& Entry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "PushEntry");

	Params::WDChatBP_C_PushEntry Parms{};

	Parms.Entry = std::move(Entry);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDChatBP.WDChatBP_C.UpdateChatButton
// (Event, Public, BlueprintEvent)

void UWDChatBP_C::UpdateChatButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "UpdateChatButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.UpdateTimeOutProgress
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   Progress                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWDChatBP_C::UpdateTimeOutProgress(float Progress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "UpdateTimeOutProgress");

	Params::WDChatBP_C_UpdateTimeOutProgress Parms{};

	Parms.Progress = Progress;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDChatBP.WDChatBP_C.SetChatText
// (Event, Public, BlueprintEvent)
// Parameters:
// class FString                           Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWDChatBP_C::SetChatText(const class FString& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "SetChatText");

	Params::WDChatBP_C_SetChatText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDChatBP.WDChatBP_C.BndEvt__TribeChannelButton_K2Node_ComponentBoundEvent_147_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__TribeChannelButton_K2Node_ComponentBoundEvent_147_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__TribeChannelButton_K2Node_ComponentBoundEvent_147_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.BndEvt__GlobalChannelButton_K2Node_ComponentBoundEvent_123_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWDChatBP_C::BndEvt__GlobalChannelButton_K2Node_ComponentBoundEvent_123_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "BndEvt__GlobalChannelButton_K2Node_ComponentBoundEvent_123_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.ShowChannelButtonsBP
// (Public, BlueprintCallable, BlueprintEvent)

void UWDChatBP_C::ShowChannelButtonsBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "ShowChannelButtonsBP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.UpdateChatButtonBP
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWDChatBP_C::UpdateChatButtonBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "UpdateChatButtonBP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.PushQuickEntry
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FChatEntry                       Entry                                                  (BlueprintVisible, BlueprintReadOnly, Parm)

void UWDChatBP_C::PushQuickEntry(const struct FChatEntry& Entry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "PushQuickEntry");

	Params::WDChatBP_C_PushQuickEntry Parms{};

	Parms.Entry = std::move(Entry);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDChatBP.WDChatBP_C.PushWindowEntry
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FChatEntry                       Entry                                                  (BlueprintVisible, BlueprintReadOnly, Parm)

void UWDChatBP_C::PushWindowEntry(const struct FChatEntry& Entry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "PushWindowEntry");

	Params::WDChatBP_C_PushWindowEntry Parms{};

	Parms.Entry = std::move(Entry);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDChatBP.WDChatBP_C.AddWindowEntry
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FChatEntry                       Entry                                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UUI_WDChatText*                   Created                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWDChatBP_C::AddWindowEntry(struct FChatEntry& Entry, class UUI_WDChatText** Created)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "AddWindowEntry");

	Params::WDChatBP_C_AddWindowEntry Parms{};

	Parms.Entry = std::move(Entry);

	UObject::ProcessEvent(Func, &Parms);

	Entry = std::move(Parms.Entry);

	if (Created != nullptr)
		*Created = Parms.Created;
}


// Function WDChatBP.WDChatBP_C.SetWindowTab
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NewTab                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWDChatBP_C::SetWindowTab(int32 NewTab)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "SetWindowTab");

	Params::WDChatBP_C_SetWindowTab Parms{};

	Parms.NewTab = NewTab;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDChatBP.WDChatBP_C.RebuildChatWindow
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWDChatBP_C::RebuildChatWindow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "RebuildChatWindow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.ScrollEnd
// (Public, BlueprintCallable, BlueprintEvent)

void UWDChatBP_C::ScrollEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "ScrollEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.ClearChat
// (Public, BlueprintCallable, BlueprintEvent)

void UWDChatBP_C::ClearChat()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "ClearChat");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.TryClear
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWDChatTextBP_C*                  ChatInstance                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    CheckNext                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWDChatBP_C::TryClear(class UWDChatTextBP_C* ChatInstance, bool* CheckNext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "TryClear");

	Params::WDChatBP_C_TryClear Parms{};

	Parms.ChatInstance = ChatInstance;

	UObject::ProcessEvent(Func, &Parms);

	if (CheckNext != nullptr)
		*CheckNext = Parms.CheckNext;
}


// Function WDChatBP.WDChatBP_C.SubmitAutoTextAndHide
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    WithSarcasm                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UButton*                          ForButton                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWDChatBP_C::SubmitAutoTextAndHide(bool WithSarcasm, class UButton* ForButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "SubmitAutoTextAndHide");

	Params::WDChatBP_C_SubmitAutoTextAndHide Parms{};

	Parms.WithSarcasm = WithSarcasm;
	Parms.ForButton = ForButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WDChatBP.WDChatBP_C.SarcasticPressed
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWDChatBP_C::SarcasticPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "SarcasticPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.SarcasticCheck
// (Public, BlueprintCallable, BlueprintEvent)

void UWDChatBP_C::SarcasticCheck()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "SarcasticCheck");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.SetupButtonAutoText
// (Public, BlueprintCallable, BlueprintEvent)

void UWDChatBP_C::SetupButtonAutoText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "SetupButtonAutoText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.IsExpanded
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UWDChatBP_C::IsExpanded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "IsExpanded");

	Params::WDChatBP_C_IsExpanded Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WDChatBP.WDChatBP_C.CheckRebuildTribeChat
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EChatChannel                            NewChatChannel                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ShouldRebuild                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UWDChatBP_C::CheckRebuildTribeChat(EChatChannel NewChatChannel, bool* ShouldRebuild)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "CheckRebuildTribeChat");

	Params::WDChatBP_C_CheckRebuildTribeChat Parms{};

	Parms.NewChatChannel = NewChatChannel;

	UObject::ProcessEvent(Func, &Parms);

	if (ShouldRebuild != nullptr)
		*ShouldRebuild = Parms.ShouldRebuild;
}


// Function WDChatBP.WDChatBP_C.UpdateTribeTab
// (Public, BlueprintCallable, BlueprintEvent)

void UWDChatBP_C::UpdateTribeTab()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "UpdateTribeTab");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WDChatBP.WDChatBP_C.GetButtonChatIndex
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class UButton*                          Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_Index                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWDChatBP_C::GetButtonChatIndex(class UButton* Button, int32* Param_Index) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WDChatBP_C", "GetButtonChatIndex");

	Params::WDChatBP_C_GetButtonChatIndex Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);

	if (Param_Index != nullptr)
		*Param_Index = Parms.Param_Index;
}

}

