#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WDChatTextBP

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "ShooterGame_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WDChatTextBP.WDChatTextBP_C
// 0x0018 (0x03F8 - 0x03E0)
class UWDChatTextBP_C final : public UUI_WDChatText
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E0(0x0008)(Transient, DuplicateTransient)
	class UImage*                                 Channel;                                           // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UPrimalRichTextBlock*                   Text;                                              // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WDChatTextBP(int32 EntryPoint);
	void Construct();
	void Setup(const class FString& Param_Text, class UTexture2D* Texture, const struct FColor& IconColor);
	void Copy(class UWDChatTextBP_C* Other);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WDChatTextBP_C">();
	}
	static class UWDChatTextBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWDChatTextBP_C>();
	}
};

}

