#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WDRecording

#include "Basic.hpp"


namespace SDK::Params
{

// Function WDRecording.WDRecording_C.ExecuteUbergraph_WDRecording
// 0x0030 (0x0030 - 0x0000)
struct WDRecording_C_ExecuteUbergraph_WDRecording final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Event_text;                                 // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0018(0x0018)()
};

// Function WDRecording.WDRecording_C.SetTimerText
// 0x0010 (0x0010 - 0x0000)
struct WDRecording_C_SetTimerText final
{
public:
	class FString                                 Text;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};

}

