#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WoodHarvestComponent_LessWood

#include "Basic.hpp"

#include "WoodHarvestComponent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WoodHarvestComponent_LessWood.WoodHarvestComponent_LessWood_C
// 0x0000 (0x0380 - 0x0380)
class UWoodHarvestComponent_LessWood_C final : public UWoodHarvestComponent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WoodHarvestComponent_LessWood_C">();
	}
	static class UWoodHarvestComponent_LessWood_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWoodHarvestComponent_LessWood_C>();
	}
};

}

