name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.app || sudo xcode-select -s /Applications/Xcode_16.0.app || sudo xcode-select -s /Applications/Xcode_16.1.app

      - name: Build Project
        run: |
          xcodebuild -project Dragon.xcodeproj \
                     -scheme Dragon \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath build/Dragon.xcarchive \
                     archive \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_IDENTITY=""

      - name: Package Payload to IPA
        run: |
          mkdir -p Payload
          cp -r build/Dragon.xcarchive/Products/Applications/*.app Payload/
          zip -r Dragon.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dragon-IPA-Package
          path: Dragon.ipa
